print("        <div class=\"nav\">");
print("            <ul class=\"navmenu\">");
print("                <li>");
print("                    <a href='zoneview.html'>Zones</a>");
print("                </li>");
print("                <li>");
print("                    <a href='playerview.html'>Players</a>");
print("                </li>");
print("                <li>");
print("                    <a href='bugview.html'>Bugs</a>");
print("                </li>");
print("            </ul>");
print("        </div>");