print("        <div class=\"nav\">");
print("            <ul class=\"navmenu\">");
print("                <li>");
print("                    <a href='index.html'>World</a>");
print("                    <ul>");
print("                        <li><a href='launchers.html'>Launchers</a></li>");
print("                        <li><a href='players.html'>Players</a></li>");
print("                        <li><a href='zones.html'>Zones</a></li>");
print("                    </ul>");
print("                </li>");
print("                <li>");
print("                    <a href='console.html'>Console</a>");
print("                </li>");
print("                <li>");
print("                    <a href='bugs.html'>Bugs</a>");
print("                </li>");
print("            </ul>");
print("        </div>");