
//list of packets we need to encode on the way out:
E(OP_LogServer)
E(OP_SendMembership)
E(OP_SendMembershipDetails)
E(OP_SendMaxCharacters)
E(OP_SendCharInfo)
E(OP_ExpansionInfo)
E(OP_SpawnAppearance)
//E(OP_SendAATable)
E(OP_PlayerProfile)
E(OP_ZoneEntry)
E(OP_ZoneSpawns)
E(OP_CharInventory)
E(OP_NewZone)
E(OP_SpawnDoor)
E(OP_GroundSpawn)
E(OP_SendZonepoints)
E(OP_RequestClientZoneChange)
E(OP_ZoneChange)
E(OP_ClientUpdate)
E(OP_WearChange)
E(OP_ChannelMessage)
E(OP_SpecialMesg)
E(OP_DeleteSpawn)
//list of packets we need to decode on the way in:
D(OP_EnterWorld)
D(OP_ZoneEntry)
D(OP_ZoneChange)
D(OP_ClientUpdate)
D(OP_WearChange)
D(OP_ChannelMessage)

#undef E
#undef D
