 -- delete grids
DELETE FROM grid 
WHERE zoneid = 202
AND id IN (SELECT DISTINCT gridid 
FROM grid_entries 
WHERE zoneid = 202
AND gridid IN ( SELECT s2.pathgrid FROM spawn2 s2, spawngroup sg, spawnentry se, npc_types nt 
WHERE  nt.name IN ('Guardian_Aderrawyn', 'Guardian_Caynd', 
'a_frightening_liaison', 'Guardian_Jarenth', 'Guardian_Rhilali', 
'Guardian_Bomawyn', 'Guardian_Adiasean', 'Guardian_Norerd', 'Guardian_Erohach', 
'Guardian_Frilikin', 'Guardian_Asirav', 'Guardian_Voelath', 'Guardian_Helind', 
'Guardian_Frendad', 'Guardian_Rirak', 'Guardian_Jelab', 'Guardian_Cigosh', 
'Frozen_Skeleton_of_the_Cursed', 'Guardian_Onaut', 'Guardian_Rhenwan', 
'Guardian_Kedirakith', 'Guardian_Onay', 'Guardian_Drendle', 'Guardian_Vaehan', 
'Guardian_Prau', 'Guardian_Shabado', 'Guardian_Daknot', 'Guardian_Aboekor', 
'Guardian_Adew', 'Guardian_Rhorin', 'Facesmasher_Brog', 'Guardian_Ulaurd', 
'Guardian_Wedrijan', 'Guardian_Jerbabi', 'Guardian_Thaowyn') 
AND s2.spawngroupID = sg.id 
AND s2.zone = 'poknowledge'
AND sg.ID = se.spawngroupID
AND se.npcID = nt.id));  

 -- delete grid entries
DELETE FROM grid_entries 
WHERE zoneid = 202
AND gridid IN ( SELECT s2.pathgrid FROM spawn2 s2, spawngroup sg, spawnentry se, npc_types nt 
WHERE  nt.name IN ('Guardian_Aderrawyn', 'Guardian_Caynd', 
'a_frightening_liaison', 'Guardian_Jarenth', 'Guardian_Rhilali', 
'Guardian_Bomawyn', 'Guardian_Adiasean', 'Guardian_Norerd', 'Guardian_Erohach', 
'Guardian_Frilikin', 'Guardian_Asirav', 'Guardian_Voelath', 'Guardian_Helind', 
'Guardian_Frendad', 'Guardian_Rirak', 'Guardian_Jelab', 'Guardian_Cigosh', 
'Frozen_Skeleton_of_the_Cursed', 'Guardian_Onaut', 'Guardian_Rhenwan', 
'Guardian_Kedirakith', 'Guardian_Onay', 'Guardian_Drendle', 'Guardian_Vaehan', 
'Guardian_Prau', 'Guardian_Shabado', 'Guardian_Daknot', 'Guardian_Aboekor', 
'Guardian_Adew', 'Guardian_Rhorin', 'Facesmasher_Brog', 'Guardian_Ulaurd', 
'Guardian_Wedrijan', 'Guardian_Jerbabi', 'Guardian_Thaowyn') 
AND s2.spawngroupID = sg.id 
AND s2.zone = 'poknowledge'
AND sg.ID = se.spawngroupID
AND se.npcID = nt.id); 

 -- remove spawn2 pathgrid
UPDATE spawn2 SET pathgrid = 0
WHERE zone = 'poknowledge'
AND spawngroupID IN ( SELECT DISTINCT sg.id FROM spawngroup sg, spawnentry se, npc_types nt 
WHERE  nt.name IN ('Guardian_Aderrawyn', 'Guardian_Caynd', 
'a_frightening_liaison', 'Guardian_Jarenth', 'Guardian_Rhilali', 
'Guardian_Bomawyn', 'Guardian_Adiasean', 'Guardian_Norerd', 'Guardian_Erohach', 
'Guardian_Frilikin', 'Guardian_Asirav', 'Guardian_Voelath', 'Guardian_Helind', 
'Guardian_Frendad', 'Guardian_Rirak', 'Guardian_Jelab', 'Guardian_Cigosh', 
'Frozen_Skeleton_of_the_Cursed', 'Guardian_Onaut', 'Guardian_Rhenwan', 
'Guardian_Kedirakith', 'Guardian_Onay', 'Guardian_Drendle', 'Guardian_Vaehan', 
'Guardian_Prau', 'Guardian_Shabado', 'Guardian_Daknot', 'Guardian_Aboekor', 
'Guardian_Adew', 'Guardian_Rhorin', 'Facesmasher_Brog', 'Guardian_Ulaurd', 
'Guardian_Wedrijan', 'Guardian_Jerbabi', 'Guardian_Thaowyn') 
AND sg.ID = se.spawngroupID
AND se.npcID = nt.id); 

--  UPDATE merc merchant npc_types
UPDATE npc_types set texture = 3, helmtexture = 0, size = 7, gender = 1, race = 2, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1, lastname = 'Barbarian Mercenary Liaison' where name = 'Guardian_Aderrawyn';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 7, gender = 0, race = 2, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0, lastname = 'Barbarian Mercenary Liaison' where name = 'Guardian_Caynd';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5.5, gender = 0, race = 7, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Half Elf Mercenary Liaison' where name = 'Guardian_Jarenth';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5.5, gender = 1, race = 7, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Half Elf Mercenary Liaison' where name = 'Guardian_Rhilali';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 0, race = 3, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Erudite Mercenary Liaison' where name = 'Guardian_Bomawyn';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 1, race = 3, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Erudite Mercenary Liaison' where name = 'Guardian_Adiasean';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 0, race = 330, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Froglok Mercenary Liaison' where name = 'Guardian_Norerd';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 1, race = 330, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Froglok Mercenary Liaison' where name = 'Guardian_Erohach';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 3, gender = 0, race = 12, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Gnome Mercenary Liaison' where name = 'Guardian_Frilikin';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 3, gender = 1, race = 12, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Gnome Mercenary Liaison' where name = 'Guardian_Asirav';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 7, gender = 0, race = 130, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Vah Shir Mercenary Liaison' where name = 'Guardian_Voelath';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 7, gender = 1, race = 130, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Vah Shir Mercenary Liaison' where name = 'Guardian_Helind';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 1, race = 128, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Iksar Mercenary Liaison' where name = 'Guardian_Frendad';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 4, gender = 1, race = 8, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Dwarf Mercenary Liaison' where name = 'Guardian_Rirak';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 0, race = 128, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Iksar Mercenary Liaison' where name = 'Guardian_Jelab';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 4, gender = 0, race = 8, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Dwarf Mercenary Liaison' where name = 'Guardian_Cigosh';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 0, race = 5, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'High Elf Mercenary Liaison' where name = 'Guardian_Onaut';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 1, race = 5, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'High Elf Mercenary Liaison' where name = 'Guardian_Rhenwan';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 0, race = 6, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Dark Elf Mercenary Liaison' where name = 'Guardian_Kedirakith';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 1, race = 6, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Dark Elf Mercenary Liaison' where name = 'Guardian_Onay';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 1, race = 1, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Human Mercenary Liaison' where name = 'Guardian_Drendle';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 0, race = 1, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Human Mercenary Liaison' where name = 'Guardian_Vaehan';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 0, race = 4, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Wood Elf Mercenary Liaison' where name = 'Guardian_Prau';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5, gender = 1, race = 4, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Wood Elf Mercenary Liaison' where name = 'Guardian_Shabado';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 9, gender = 1, race = 10, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Ogre Mercenary Liaison' where name = 'Guardian_Daknot';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 6, gender = 0, race = 522, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Drakkin Mercenary Liaison' where name = 'Guardian_Aboekor';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 5.7, gender = 1, race = 522, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Drakkin Mercenary Liaison' where name = 'Guardian_Adew';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 9, gender = 0, race = 10, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Ogre Mercenary Liaison' where name = 'Guardian_Rhorin';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 8, gender = 1, race = 9, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Troll Mercenary Liaison' where name = 'Guardian_Ulaurd';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 8, gender = 0, race = 9, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Troll Mercenary Liaison' where name = 'Guardian_Wedrijan';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 3.5, gender = 0, race = 11, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 0 , lastname = 'Halfling Mercenary Liaison' where name = 'Guardian_Jerbabi';
UPDATE npc_types set texture = 3, helmtexture = 0, size = 3.5, gender = 1, race = 11, class = 71, level = 99, hp = 10791, face = 0, luclin_hairstyle = 0, luclin_haircolor = 0, luclin_eyecolor = 0, luclin_eyecolor2 = 0, luclin_beardcolor = 0, luclin_beard = 255, drakkin_heritage = 0, drakkin_tattoo = 0, drakkin_details = 0, armortint_red = 0, armortint_green = 0, armortint_blue = 0, d_meele_texture1 = 0, d_meele_texture2 = 0, findable = True, gender = 1 , lastname = 'Halfling Mercenary Liaison' where name = 'Guardian_Thaowyn';

-- UPDATE merc merchant spawn locations
UPDATE spawn2 SET x = -188, y = 216, z = -109.5, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Aderrawyn' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = -213, y = 216, z = -109.5, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Caynd' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = -0.375, y = -41.875, z = -155.125, heading = 189.5 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'a_frightening_liaison' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 83, y = 10, z = -80.5, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Jarenth' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 83, y = -9, z = -80.5, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Rhilali' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 170, y = 170, z = -123.875, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Bomawyn' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 170, y = 200, z = -123.875, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Adiasean' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 172, y = -173, z = -124.75, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Norerd' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 172, y = -203, z = -124.75, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Erohach' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 258, y = 533, z = -158, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Frilikin' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 288, y = 533, z = -158, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Asirav' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 444, y = 429, z = -123.5, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Voelath' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 444, y = 449, z = -123.5, heading = 192 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Helind' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 260, y = -533, z = -156.125, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Frendad' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 566, y = 25, z = 2.5, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Rirak' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 290, y = -533, z = -156.125, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Jelab' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 570, y = -25, z = 2.5, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Cigosh' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 234.875, y = -824.375, z = -156.125, heading = 215 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Frozen_Skeleton_of_the_Cursed' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 700, y = 533, z = -124.125, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Onaut' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 730, y = 533, z = -124.125, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Rhenwan' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 700, y = -533, z = -124.75, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Kedirakith' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 730, y = -533, z = -124.75, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Onay' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 904, y = 274, z = -1.375, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Drendle' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 948, y = 274, z = -1, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Vaehan' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 667, y = 842, z = -110.75, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Prau' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 667, y = 871, z = -110.75, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Shabado' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1000, y = -223, z = 6, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Daknot' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 917, y = 648, z = -79.875, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Aboekor' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 937, y = 648, z = -80.125, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Adew' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1050, y = -223, z = 6, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Rhorin' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1070, y = -461, z = -122.875, heading = 0 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Facesmasher_Brog' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1017, y = -636, z = -78.875, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Ulaurd' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1035, y = -636, z = -78.875, heading = 128 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Wedrijan' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1404, y = 68, z = -109.75, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Jerbabi' LIMIT 1) AND sg.id = se.spawngroupID);
UPDATE spawn2 SET x = 1404, y = -68, z = -109.75, heading = 64 WHERE spawngroupID = (SELECT sg.id FROM spawngroup sg, spawnentry se WHERE se.npcID = (SELECT ID FROM npc_types WHERE name = 'Guardian_Thaowyn' LIMIT 1) AND sg.id = se.spawngroupID);
