DROP TABLE IF EXISTS bots;
CREATE TABLE IF NOT EXISTS bots (
  BotID integer unsigned NOT NULL auto_increment,
  BotOwnerAccountID integer unsigned NOT NULL,
  BotInventoryID integer unsigned NOT NULL default 0,
  BotSpellsID integer unsigned NOT NULL default 0,
  Name varchar(64) NOT NULL,
  LastName varchar(32) default NULL,
  /*ExpPoints integer unsigned NOT NULL default 0,
  AAPoints integer unsigned NOT NULL default 0,*/
  BotLevel tinyint(2) unsigned NOT NULL default 0,
  Race smallint(5) unsigned not NULL default 0,
  Class tinyint(2) unsigned NOT NULL default 0,
  BodyType int(11) default NULL,
  HitPoints int(11) NOT NULL default 0,
  Gender tinyint(2) unsigned NOT NULL default 0,
  Size float NOT NULL default 0,
  HitPointsRegenRate int(11) unsigned NOT NULL default 0,
  ManaRegenRate int(11) unsigned NOT NULL default 0,
  Face int(10) unsigned NOT NULL default 1,
  LuclinHairStyle int(10) unsigned NOT NULL default 1,
  LuclinHairColor int(10) unsigned NOT NULL default 1,
  LuclinEyeColor int(10) unsigned NOT NULL default 1,
  LuclinEyeColor2 int(10) unsigned NOT NULL default 1,
  LuclinBeardColor int(10) unsigned NOT NULL default 1,
  LuclinBeard int(10) unsigned NOT NULL default 0,
  DrakkinHeritage int(10) unsigned NOT NULL default 0,
  DrakkinTattoo int(10) unsigned NOT NULL default 0,
  DrakkinDetails int(10) unsigned NOT NULL default 0,
  RunSpeed float NOT NULL default 0,
  MR smallint(5) NOT NULL default 0,
  CR smallint(5) NOT NULL default 0,
  DR smallint(5) NOT NULL default 0,
  FR smallint(5) NOT NULL default 0,
  PR smallint(5) NOT NULL default 0,
  AC smallint(5) NOT NULL default 0,
  STR mediumint(8) unsigned NOT NULL default 75,
  STA mediumint(8) unsigned NOT NULL default 75,
  DEX mediumint(8) unsigned NOT NULL default 75,
  AGI mediumint(8) unsigned NOT NULL default 75,
  _INT mediumint(8) unsigned NOT NULL default 80,
  WIS mediumint(8) unsigned NOT NULL default 75,
  CHA mediumint(8) unsigned NOT NULL default 75,
  ATK mediumint(9) NOT NULL default 0,
  PRIMARY KEY (BotID)
) ENGINE=InnoDB;