#ifndef STRING_IDS
#define STRING_IDS

//These strings are loaded from eqstr_us.txt, but may vary between client versions. Maybe we could make this an enum that's dependent on the client version?
namespace ClientString {
	constexpr int GENERIC_9_STRINGS              = 1; //%1 %2 %3 %4 %5 %6 %7 %8 %9
	constexpr int TARGET_OUT_OF_RANGE            = 100; //Your target is out of range, get closer!
	constexpr int TARGET_NOT_FOUND               = 10; //Target player not found.
	constexpr int TRADE_CANCEL_LORE              = 104; //Trade cancelled, duplicated Lore Items would result.
	constexpr int CANNOT_BIND                    = 105; //You cannot form an affinity with this area. Try a city.
	constexpr int SPELL_DOES_NOT_WORK_HERE       = 106; //This spell does not work here.
	constexpr int SPELL_DOES_NOT_WORK_PLANE      = 107; //This spell does not work on this plane.
	constexpr int CANT_SEE_TARGET                = 108; //You cannot see your target.
	constexpr int MGB_STRING                     = 113; //The next group buff you cast will hit all targets in range.
	constexpr int ABILITY_FAILED                 = 116; //Your ability failed. Timer has been reset.
	constexpr int ESCAPE                         = 114; //You escape from combat, hiding yourself from view.
	constexpr int AA_OFF                         = 119; //Alternate Experience is *OFF*.
	constexpr int AA_ON                          = 121; //Alternate Experience is *ON*.
	constexpr int TARGET_TOO_FAR                 = 124; //Your target is too far away, get closer!
	constexpr int PROC_TOOLOW                    = 126; //Your will is not sufficient to command this weapon.
	constexpr int PROC_PETTOOLOW                 = 127; //Your pet's will is not sufficient to command its weapon.
	constexpr int YOU_FLURRY                     = 128; //You unleash a flurry of attacks.
	constexpr int FAILED_DISARM_TRAP             = 129; //You failed to disarm the trap.
	constexpr int DOORS_LOCKED                   = 130; //It's locked and you're not holding the key.
	constexpr int DOORS_CANT_PICK                = 131; //This lock cannot be picked.
	constexpr int DOORS_INSUFFICIENT_SKILL       = 132; //You are not sufficiently skilled to pick this lock.
	constexpr int DOORS_GM                       = 133; //You opened the locked door with your magic GM key.
	constexpr int ITEMS_INSUFFICIENT_LEVEL       = 136; //You are not sufficient level to use this item.
	constexpr int GAIN_XP                        = 138; //You gain experience!!
	constexpr int GAIN_GROUPXP                   = 139; //You gain party experience!!
	constexpr int BOW_DOUBLE_DAMAGE              = 143; //Your bow shot did double dmg.
	constexpr int YOU_ARE_BEING_BANDAGED         = 147; //Someone is bandaging you.
	constexpr int FORAGE_GRUBS                   = 150; //You have scrounged up some fishing grubs.
	constexpr int FORAGE_WATER                   = 151; //You have scrounged up some water.
	constexpr int FORAGE_FOOD                    = 152; //You have scrounged up some food.
	constexpr int FORAGE_DRINK                   = 153; //You have scrounged up some drink.
	constexpr int FORAGE_NOEAT                   = 154; //You have scrounged up something that doesn't look edible.
	constexpr int FORAGE_FAILED                  = 155; //You fail to locate any food nearby.
	constexpr int ALREADY_FISHING                = 156; //You are already fishing!
	constexpr int FISHING_NO_POLE                = 160; //You can't fish without a fishing pole, go buy one.
	constexpr int FISHING_EQUIP_POLE             = 161; //You need to put your fishing pole in your primary hand.
	constexpr int FISHING_NO_BAIT                = 162; //You can't fish without fishing bait, go buy some.
	constexpr int FISHING_CAST                   = 163; //You cast your line.
	constexpr int NOT_SCARING                    = 164; //You're not scaring anyone.
	constexpr int FISHING_STOP                   = 165; //You stop fishing and go on your way.
	constexpr int FISHING_LAND                   = 166; //Trying to catch land sharks perhaps?
	constexpr int FISHING_LAVA                   = 167; //Trying to catch a fire elemental or something?
	constexpr int FISHING_FAILED                 = 168; //You didn't catch anything.
	constexpr int FISHING_POLE_BROKE             = 169; //Your fishing pole broke!
	constexpr int FISHING_SUCCESS                = 170; //You caught, something...
	constexpr int FISHING_SPILL_BEER             = 171; //You spill your beer while bringing in your line.
	constexpr int FISHING_LOST_BAIT              = 172; //You lost your bait!
	constexpr int SPELL_FIZZLE                   = 173; //Your spell fizzles!
	constexpr int MUST_EQUIP_ITEM                = 179; //You cannot use this item unless it is equipped.
	constexpr int MISS_NOTE                      = 180; //You miss a note, bringing your song to a close!
	constexpr int CANNOT_USE_ITEM                = 181; //Your race, class, or deity cannot use this item.
	constexpr int ITEM_OUT_OF_CHARGES            = 182; //Item is out of charges.
	constexpr int ALREADY_ON_A_MOUNT             = 189; //You are already on a mount.
	constexpr int TARGET_NO_MANA                 = 191; //Your target has no mana to affect
	constexpr int TARGET_GROUP_MEMBER            = 196; //You must first target a group member.
	constexpr int SPELL_TOO_POWERFUL             = 197; //Your spell is too powerful for your intended target.
	constexpr int INSUFFICIENT_MANA              = 199; //Insufficient Mana to cast this spell!
	constexpr int SAC_TOO_LOW                    = 203; //This being is not a worthy sacrifice.
	constexpr int SAC_TOO_HIGH                   = 204; //This being is too powerful to be a sacrifice.
	constexpr int CANNOT_SAC_SELF                = 205; //You cannot sacrifice yourself.
	constexpr int SILENCED_STRING                = 207; //You *CANNOT* cast spells, you have been silenced!
	constexpr int CAST_DAYTIME                   = 208; //Spell can only be cast during the day.
	constexpr int CAST_NIGHTTIME                 = 209; //Spell can only be cast during the night.
	constexpr int CANNOT_AFFECT_PC               = 210; //That spell can not affect this target PC.
	constexpr int SPELL_NEED_TAR                 = 214; //You must first select a target for this spell!
	constexpr int SUMMON_ONLY_GROUP_CORPSE       = 215; //You must first target a living group member whose corpse you wish to summon.
	constexpr int ONLY_ON_CORPSES                = 221; //This spell only works on corpses.
	constexpr int CANT_DRAIN_SELF                = 224; //You can't drain yourself!
	constexpr int CORPSE_NOT_VALID               = 230; //This corpse is not valid.
	constexpr int CORPSE_TOO_OLD                 = 231; //This player cannot be resurrected. The corpse is too old.
	constexpr int CAST_OUTDOORS                  = 234; //You can only cast this spell in the outdoors.
	constexpr int SPELL_RECAST                   = 236; //Spell recast time not yet met.
	constexpr int SPELL_RECOVERY                 = 237; //Spell recovery time not yet met.
	constexpr int CANNOT_MEZ                     = 239; //Your target cannot be mesmerized.
	constexpr int CANNOT_MEZ_WITH_SPELL          = 240; //Your target cannot be mesmerized (with this spell).
	constexpr int IMMUNE_STUN                    = 241; //Your target is immune to the stun portion of this effect.
	constexpr int IMMUNE_ATKSPEED                = 242; //Your target is immune to changes in its attack speed.
	constexpr int IMMUNE_FEAR                    = 243; //Your target is immune to fear spells.
	constexpr int IMMUNE_MOVEMENT                = 244; //Your target is immune to changes in its run speed.
	constexpr int ONLY_ONE_PET                   = 246; //You cannot have more than one pet at a time.
	constexpr int CANNOT_CHARM_YET               = 248; //Your target is too high of a level for your charm spell.
	constexpr int CANNOT_AFFECT_NPC              = 251; //That spell can not affect this target NPC.
	constexpr int FD_CAST_ON                     = 254; //You are no longer feigning death, because a spell hit you.
	constexpr int SUSPEND_MINION_HAS_AGGRO       = 256; //Your pet is the focus of something's attention.
	constexpr int NO_PET                         = 255; //You do not have a pet.
	constexpr int GATE_FAIL                      = 260; //Your gate is too unstable, and collapses.
	constexpr int CORPSE_CANT_SENSE              = 262; //You cannot sense any corpses for this PC in this zone.
	constexpr int SPELL_NO_HOLD                  = 263; //Your spell did not take hold.
	constexpr int CANNOT_CHARM                   = 267; //This NPC cannot be charmed.
	constexpr int SPELL_NO_EFFECT                = 268; //Your target looks unaffected.
	constexpr int NO_INSTRUMENT_SKILL            = 269; //Stick to singing until you learn to play this instrument.
	constexpr int REGAIN_AND_CONTINUE            = 270; //You regain your concentration and continue your casting.
	constexpr int SPELL_WOULDNT_HOLD             = 271; //Your spell would not have taken hold on your target.
	constexpr int MISSING_SPELL_COMP             = 272; //You are missing some required spell components.
	constexpr int INVIS_BEGIN_BREAK              = 275; //You feel yourself starting to appear.
	constexpr int DISCIPLINE_CONLOST             = 278; //You lose the concentration to remain in your fighting discipline.
	constexpr int REZ_REGAIN                     = 289; //You regain some experience from resurrection.
	constexpr int DUP_LORE                       = 290; //Duplicate lore items are not allowed.
	constexpr int TGB_ON                         = 293; //Target other group buff is *ON*.
	constexpr int TGB_OFF                        = 294; //Target other group buff is *OFF*.
	constexpr int DONT_SEE_TARGET                = 303; //I don't see anyone by that name around here...
	constexpr int DISARMED_TRAP                  = 305; //You have disarmed the trap.
	constexpr int LDON_SENSE_TRAP1               = 306; //You do not Sense any traps.
	constexpr int TRADESKILL_NOCOMBINE           = 334; //You cannot combine these items in this container type!
	constexpr int TRADESKILL_FAILED              = 336; //You lacked the skills to fashion the items together.
	constexpr int TRADESKILL_TRIVIAL             = 338; //You can no longer advance your skill from making this item.
	constexpr int TRADESKILL_SUCCEED             = 339; //You have fashioned the items together to create something new!
	constexpr int EVADE_SUCCESS                  = 343; //You have momentarily ducked away from the main combat.
	constexpr int EVADE_FAIL                     = 344; //Your attempts at ducking clear of combat fail.
	constexpr int HIDE_FAIL                      = 345; //You failed to hide yourself.
	constexpr int HIDE_SUCCESS                   = 346; //You have hidden yourself from view.
	constexpr int SNEAK_SUCCESS                  = 347; //You are as quiet as a cat stalking its prey.
	constexpr int SNEAK_FAIL                     = 348; //You are as quiet as a herd of running elephants.
	constexpr int MEND_CRITICAL                  = 349; //You magically mend your wounds and heal considerable damage.
	constexpr int MEND_SUCCESS                   = 350; //You mend your wounds and heal some damage.
	constexpr int MEND_WORSEN                    = 351; //You have worsened your wounds!
	constexpr int MEND_FAIL                      = 352; //You have failed to mend your wounds.
	constexpr int LDON_SENSE_TRAP2               = 367; //You have not detected any traps.
	constexpr int TRAP_TOO_FAR                   = 368; //You are too far away from that trap to affect it.
	constexpr int FAIL_DISARM_DETECTED_TRAP      = 370; //You fail to disarm the detected trap.
	constexpr int LOOT_LORE_ERROR                = 371; //You cannot loot this Lore Item. You already have one.
	constexpr int PICK_LORE                      = 379; //You cannot pick up a lore item you already possess.
	constexpr int POISON_TOO_HIGH                = 382; //This poison is too high level for you to apply.
	constexpr int TAUNT_TOO_FAR                  = 386; //You are too far away from your target to taunt.
	constexpr int CORPSE_TOO_FAR                 = 389; //The corpse is too far away to summon.
	constexpr int CONSENT_DENIED                 = 390; //You do not have consent to summon that corpse.
	constexpr int DISCIPLINE_RDY                 = 393; //You are ready to use a new discipline now.
	constexpr int CONSENT_INVALID_NAME           = 397; //Not a valid consent name.
	constexpr int CONSENT_NPC                    = 398; //You cannot consent NPC\'s.
	constexpr int CONSENT_YOURSELF               = 399; //You cannot consent yourself.
	constexpr int CONSENT_WAIT                   = 400; //You must wait 2 seconds between consents.
	constexpr int SONG_NEEDS_DRUM                = 405; //You need to play a percussion instrument for this song
	constexpr int SONG_NEEDS_WIND                = 406; //You need to play a wind instrument for this song
	constexpr int SONG_NEEDS_STRINGS             = 407; //You need to play a stringed instrument for this song
	constexpr int SONG_NEEDS_BRASS               = 408; //You need to play a brass instrument for this song
	constexpr int AA_GAIN_ABILITY                = 410; //You have gained the ability "%T1" at a cost of %2 ability %T3.
	constexpr int AA_IMPROVE                     = 411; //You have improved %T1 %2 at a cost of %3 ability %T4.
	constexpr int TAUNT_SUCCESS                  = 412; //You taunt %1 to ignore others and attack you!
	constexpr int AA_REUSE_MSG                   = 413; //You can use the ability %B1(1) again in %2 hour(s) %3 minute(s) %4 seconds.
	constexpr int AA_REUSE_MSG2                  = 414; //You can use the ability %B1(1) again in %2 minute(s) %3 seconds.
	constexpr int YOU_HEALED                     = 419; //%1 has healed you for %2 points of damage.
	constexpr int FISHING_SUCCESS_FISH_NAME      = 421; //You caught %1!
	constexpr int BEGINS_TO_GLOW                 = 422; //Your %1 begins to glow.
	constexpr int ALREADY_INVIS                  = 423; //%1 tries to cast an invisibility spell on you, but you are already invisible.
	constexpr int YOU_ARE_PROTECTED              = 424; //%1 tries to cast a spell on you, but you are protected.
	constexpr int TARGET_RESISTED                = 425; //Your target resisted the %1 spell.
	constexpr int YOU_RESIST                     = 426; //You resist the %1 spell!
	constexpr int YOU_CRIT_HEAL                  = 427; //You perform an exceptional heal! (%1)
	constexpr int YOU_CRIT_BLAST                 = 428; //You deliver a critical blast! (%1)
	constexpr int SUMMONING_CORPSE               = 429; //Summoning your corpse.
	constexpr int SUMMONING_CORPSE_OTHER         = 430; //Summoning %1's corpse.
	constexpr int MISSING_SPELL_COMP_ITEM        = 433; //You are missing %1.
	constexpr int OTHER_HIT_NONMELEE             = 434; //%1 was hit by non-melee for %2 points of damage.
	constexpr int SPELL_WORN_OFF_OF              = 436; //Your %1 spell has worn off of %2.
	constexpr int SPELL_WORN_OFF                 = 437; //Your %1 spell has worn off.
	constexpr int PET_TAUNTING                   = 438; //Taunting attacker, Master.
	constexpr int INTERRUPT_SPELL                = 439; //Your spell is interrupted.
	constexpr int LOSE_LEVEL                     = 442; //You LOST a level! You are now level %1!
	constexpr int GAIN_ABILITY_POINT             = 446; //You have gained an ability point! You now have %1 ability point%2.
	constexpr int GAIN_LEVEL                     = 447; //You have gained a level! Welcome to level %1!
	constexpr int LANG_SKILL_IMPROVED            = 449; //Your language skills have improved.
	constexpr int OTHER_LOOTED_MESSAGE           = 466; //--%1 has looted a %2--
	constexpr int LOOTED_MESSAGE                 = 467; //--You have looted a %1--
	constexpr int FACTION_WORST                  = 469; //Your faction standing with %1 could not possibly get any worse.
	constexpr int FACTION_WORSE                  = 470; //Your faction standing with %1 got worse.
	constexpr int FACTION_BEST                   = 471; //Your faction standing with %1 could not possibly get any better.
	constexpr int FACTION_BETTER                 = 472; //Your faction standing with %1 got better.
	constexpr int PET_REPORT_HP                  = 488; //I have %1 percent of my hit points left.
	constexpr int PET_NO_TAUNT                   = 489; //No longer taunting attackers, Master.
	constexpr int PET_DO_TAUNT                   = 490; //Taunting attackers as normal, Master.
	constexpr int CORPSE_REZ_TIME_HOUR           = 491; //This corpse's resurrection time will expire in %1 hour(s) %2 minute(s) %3 seconds.
	constexpr int CORPSE_REZ_TIME_MINUTE         = 492; //This corpse's resurrection time will expire in %1 minute(s) %2 seconds.
	constexpr int CORPSE_DECAY_TIME_DAY          = 493; //This corpse will decay in %1 day(s) %2 hour(s) %3 minute(s) %4 seconds.
	constexpr int CORPSE_DECAY_TIME_HOUR         = 494; //This corpse will decay in %1 hour(s) %2 minute(s) %3 seconds.
	constexpr int CORPSE_DECAY_TIME_MINUTE       = 495; //This corpse will decay in %1 minute(s) %2 seconds.
	constexpr int DISC_LEVEL_ERROR               = 503; //You must be a level %1 ... to use this discipline.
	constexpr int DISCIPLINE_CANUSEIN            = 504; //You can use a new discipline in %1 minutes %2 seconds.
	constexpr int SHARE_MONEY                    = 511; //%1 shares money with the group.
	constexpr int PVP_ON                         = 552; //You are now player kill and follow the ways of Discord.
	constexpr int GENERIC_STRINGID_SAY           = 554; //%1 says '%T2'
	constexpr int CANNOT_WAKE                    = 555; //%1 tells you, 'I am unable to wake %2, master.'
	constexpr int SUMMONING_CORPSE_ZONE          = 596; //Summoning %1's corpse(s).
	constexpr int TASK_NOT_RIGHT_LEVEL           = 615; //You are not at the right level for this task.
	constexpr int INVITE_GROUP_LEADER            = 679; //To invite another group into yours, please invite the leader of the other group.
	constexpr int PET_HOLD_SET_ON                = 698; //The pet hold mode has been set to on.
	constexpr int PET_HOLD_SET_OFF               = 699; //The pet hold mode has been set to off.
	constexpr int PET_FOCUS_SET_ON               = 700; //The pet focus mode has been set to on.
	constexpr int PET_FOCUS_SET_OFF              = 701; //The pet focus mode has been set to off.
	constexpr int PET_SPELLHOLD_SET_ON           = 702; //The pet spellhold mode has been set to on.
	constexpr int PET_SPELLHOLD_SET_OFF          = 703; //The pet spellhold mode has been set to off.
	constexpr int GUILD_NAME_IN_USE              = 711; //You cannot create a guild with that name, that guild already exists on this server.
	constexpr int PARCEL_DELAY                   = 734; //%1 tells you, 'You must give me a chance to send the last parcel before I can send another!'
	constexpr int PARCEL_DUPLICATE_DELETE        = 737; //Duplicate lore items are not allowed! Your duplicate %1 has been deleted!
	constexpr int PARCEL_DELIVER_3               = 741; //%1 told you, 'I will deliver the stack of %2 %3 to %4 as soon as possible!'
	constexpr int TRADER_MODE_FAILED_ROF2        = 785; //Your attempt to become a trader has failed.
	constexpr int PARCEL_INV_FULL                = 790; //%1 tells you, 'Your inventory appears full!  Unable to retrieve parceled item.'
	constexpr int AA_CAP                         = 1000; //You have reached the AA point cap, and cannot gain any further experience until some of your stored AA point pool is used.
	constexpr int GM_GAINXP	                     = 1002; //[GM] You have gained %1 AXP and %2 EXP (%3).
	constexpr int MALE_SLAYUNDEAD                = 1007; //%1's holy blade cleanses his target!(%2)
	constexpr int FEMALE_SLAYUNDEAD              = 1008; //%1's holy blade cleanses her target!(%2)
	constexpr int FINISHING_BLOW                 = 1009; //%1 scores a Finishing Blow!!
	constexpr int ASSASSINATES                   = 1016; //%1 ASSASSINATES their victim!!
	constexpr int CRIPPLING_BLOW                 = 1021; //%1 lands a Crippling Blow!(%2)
	constexpr int STAGGERS                       = 1022; //%1 staggers.
	constexpr int CRITICAL_HIT                   = 1023; //%1 scores a critical hit! (%2)
	constexpr int DEADLY_STRIKE                  = 1024; //%1 scores a Deadly Strike!(%2)
	constexpr int RESISTS_URGE                   = 1025; //%1 resists their urge to flee.
	constexpr int BERSERK_START                  = 1027; //%1 goes into a berserker frenzy!
	constexpr int DEATH_PACT                     = 1028; //%1's death pact has been benevolently fulfilled!
	constexpr int DIVINE_INTERVENTION            = 1029; //%1 has been rescued by divine intervention!
	constexpr int BERSERK_END                    = 1030; //%1 is no longer berserk.
	constexpr int GATES                          = 1031; //%1 Gates.
	constexpr int GENERIC_SAY                    = 1032; //%1 says '%2'
	constexpr int OTHER_REGAIN_CAST              = 1033; //%1 regains concentration and continues casting.
	constexpr int GENERIC_SHOUT                  = 1034; //%1 shouts '%2'
	constexpr int GENERIC_EMOTE                  = 1036; //%1 %2
	constexpr int OTHER_CRIT_HEAL                = 1039; //%1 performs an exceptional heal! (%2)
	constexpr int OTHER_CRIT_BLAST               = 1040; //%1 delivers a critical blast! (%2)
	constexpr int NPC_ENRAGE_START               = 1042; //%1 has become ENRAGED.
	constexpr int NPC_ENRAGE_END                 = 1043; //%1 is no longer enraged.
	constexpr int NPC_RAMPAGE                    = 1044; //%1 goes on a RAMPAGE!
	constexpr int NPC_FLURRY                     = 1045; //%1 executes a FLURRY of attacks on %2!
	constexpr int DISCIPLINE_FEARLESS            = 1076; //%1 becomes fearless.
	constexpr int DUEL_FINISHED                  = 1088; //dont know text
	constexpr int EATING_MESSAGE                 = 1091; //Chomp, chomp, chomp... %1 takes a bite from a %2.
	constexpr int DRINKING_MESSAGE               = 1093; //Glug, glug, glug... %1 takes a drink from a %2.
	constexpr int SUCCESSFUL_TAUNT               = 1095; //I'll teach you to interfere with me %3.
	constexpr int TRADE_BACK                     = 1105; //I have no need for this %3, you can have it back.
	constexpr int TRADE_BAD_FACTION1             = 1110; //Oh look..a talking lump of refuse..how novel!
	constexpr int TRADE_BAD_FACTION2             = 1111; //Is that your BREATH.. or did something die in here..now go away!
	constexpr int TRADE_BAD_FACTION3             = 1112; //I didn't know Slime could speak common..go back to the sewer before I lose my temper.
	constexpr int TRADE_BAD_FACTION4             = 1113; //I wonder how much I could get for the tongue of a blithering fool..leave before I decide to find out for myself.
	constexpr int PET_SIT_STRING                 = 1130; //Changing position, Master.
	constexpr int PET_CALMING                    = 1131; //Sorry, Master..calming down.
	constexpr int PET_FOLLOWING                  = 1132; //Following you, Master.
	constexpr int PET_GUARDME_STRING             = 1133; //Guarding you, Master.
	constexpr int PET_GUARDINGLIFE               = 1134; //Guarding with my life..oh splendid one.
	constexpr int PET_GETLOST_STRING             = 1135; //As you wish, oh great one.
	constexpr int PET_LEADERIS                   = 1136; //My leader is %3.
	constexpr int I_FOLLOW_NOONE                 = 1137; //I follow no one.
	constexpr int PET_ON_HOLD                    = 1138; //Waiting for your order to attack, Master.
	constexpr int NOT_LEGAL_TARGET               = 1139; //I beg forgiveness, Master. That is not a legal target.
	constexpr int MERCHANT_BUSY                  = 1143; //I'm sorry, I am busy right now.
	constexpr int MERCHANT_GREETING              = 1144; //Welcome to my shop, %3.
	constexpr int MERCHANT_HANDY_ITEM1           = 1145; //Hello there, %3. How about a nice %4?
	constexpr int MERCHANT_HANDY_ITEM2           = 1146; //Greetings, %3. You look like you could use a %4.
	constexpr int MERCHANT_HANDY_ITEM3           = 1147; //Hi there %3, just browsing? Have you seen the %4 I just got in?
	constexpr int MERCHANT_HANDY_ITEM4           = 1148; //Welcome to my shop, %3. You would probably find a %4 handy.
	constexpr int WONT_SELL_RACE1                = 1154; //I don't like to speak to %B3(12) much less sell to them!
	constexpr int WONT_SELL_CLASS1               = 1155; //It's %B3(13) like you that are ruining the continent...get OUT!
	constexpr int WONT_SELL_CLASS2               = 1156; //Isn't there some kind of ordinance against %B3(13) crawling out from under their rocks?
	constexpr int WONT_SELL_CLASS3               = 1157; //%B3(13) like you don't have any place in my shop..now make way for welcome customers.
	constexpr int WONT_SELL_CLASS4               = 1158; //I thought scumbag %B3(13) like you just stole whatever they need.  Now GET OUT!
	constexpr int WONT_SELL_CLASS5               = 1159; //I don't have anything to do with %B3(13)..move along.
	constexpr int WONT_SELL_NONSTDRACE1          = 1160; //I don't have anything to do with your little gang..move along.
	constexpr int WONT_SELL_RACE2                = 1161; //It's not enough that you %B3(12) have ruined your own land. Now get lost!
	constexpr int WONT_SELL_RACE3                = 1162; //I have something here that %B3(12) use..let me see...it's the EXIT, now get LOST!
	constexpr int WONT_SELL_RACE4                = 1163; //Don't you %B3(12) have your own merchants?  Whatever, I'm not selling anything to you!
	constexpr int WONT_SELL_NONSTDRACE2          = 1164; //Members of your little "club" have ruined things around here..get lost!
	constexpr int WONT_SELL_NONSTDRACE3          = 1165; //I don't have anything to do with your damned club..move along.
	constexpr int WONT_SELL_DEEDS1               = 1166; //Creatures like you make me sick..the things you do..get out of here Pagan!
	constexpr int WONT_SELL_DEEDS2               = 1167; //After all the things you've done..the things you believe in..leave my shop!
	constexpr int WONT_SELL_DEEDS3               = 1168; //Actions speak louder than beliefs, and I despise both your actions and all you believe in.
	constexpr int WONT_SELL_DEEDS4               = 1169; //Get out of here now!
	constexpr int WONT_SELL_DEEDS5               = 1170; //I am tolerant by nature..but infidels like you push me past my limit..get out!
	constexpr int WONT_SELL_DEEDS6               = 1171; //I cannot abide you or your actions against all that is right..BE GONE!
	constexpr int AA_POINT                       = 1197; //point
	constexpr int MERCHANT_CLOSED_ONE            = 1199; //I don't have time for that now.
	constexpr int MERCHANT_CLOSED_TWO            = 1200; //Can't you see I'm doing something here?
	constexpr int MERCHANT_CLOSED_THREE          = 1201; //I am not open for business right now.
	constexpr int AA_POINTS                      = 1215; //points
	constexpr int SPELL_FIZZLE_OTHER             = 1218; //%1's spell fizzles!
	constexpr int MISSED_NOTE_OTHER              = 1219; //A missed note brings %1's song to a close!
	constexpr int SPELL_LEVEL_REQ                = 1226; //This spell only works on people who are level %1 and under.
	constexpr int CORPSE_DECAY_NOW               = 1227; //This corpse is waiting to expire.
	constexpr int CORPSE_ITEM_LOST               = 1228; //Your items will no longer stay with you when you respawn on death. You will now need to return to your corpse for your items.
	constexpr int CORPSE_EXP_LOST                = 1229; //You will now lose experience when you die.
	constexpr int FLICKERS_PALE_LIGHT            = 1230; //Your %1 flickers with a pale light.
	constexpr int PULSES_WITH_LIGHT              = 1231; //Your %1 pulses with light as your vision sharpens.
	constexpr int FEEDS_WITH_POWER               = 1232; //Your %1 feeds you with power.
	constexpr int POWER_DRAIN_INTO               = 1233; //You feel your power drain into your %1.
	constexpr int SEEMS_DRAINED                  = 1234; //Your %1 seems drained of power.
	constexpr int ALIVE_WITH_POWER               = 1235; //Your %1 feels alive with power.
	constexpr int SPARKLES                       = 1236; //Your %1 sparkles.
	constexpr int GROWS_DIM                      = 1237; //Your %1 grows dim.
	constexpr int BEGINS_TO_SHINE                = 1238; //Your %1 begins to shine.
	constexpr int CANT_FIND_PLAYER               = 1276; //I can't find a player named %1!
	constexpr int SURNAME_REJECTED               = 1374; //Your new surname was rejected. Please try a different name.
	constexpr int ALREADY_SOLD                   = 1376; //The item you were interested in has already been sold.
	constexpr int GUILD_DISBANDED                = 1377; //Your guild has been disbanded!  You are no longer a member of any guild.
	constexpr int DUEL_DECLINE                   = 1383; //%1 has declined your challenge to duel to the death.
	constexpr int DUEL_ACCEPTED                  = 1384; //%1 has already accepted a duel with someone else.
	constexpr int DUEL_CONSIDERING               = 1385; //%1 is considering a duel with someone else.
	constexpr int PLAYER_SUMMONED                = 1393; //You have been summoned!
	constexpr int PLAYER_REGAIN                  = 1394; //You have control of yourself again.
	constexpr int REZZ_ALREADY_PENDING           = 1379; //You were unable to restore the corpse to life, but you may have success with a later attempt.
	constexpr int IN_USE                         = 1406; //Someone else is using that. Try again later.
	constexpr int DUEL_FLED                      = 1408; //%1 has defeated %2 in a duel to the death! %3 has fled like a cowardly dog!
	constexpr int MEMBER_OF_YOUR_GUILD           = 1429;
	constexpr int OFFICER_OF_YOUR_GUILD          = 1430;
	constexpr int LEADER_OF_YOUR_GUILD           = 1431;
	constexpr int TRADE_HAS_BEEN_CANCELLED       = 1449;
	constexpr int RECEIVED_PLATINUM              = 1452; //You receive %1 Platinum from %2.
	constexpr int RECEIVED_GOLD                  = 1453; //You receive %1 Gold from %2.
	constexpr int RECEIVED_SILVER                = 1454; //You receive %1 Silver from %2.
	constexpr int RECEIVED_COPPER                = 1455; //You receive %1 Copper from %2.
	constexpr int STRING_FEIGNFAILED             = 1456; //%1 has fallen to the ground.
	constexpr int DOORS_SUCCESSFUL_PICK          = 1457; //You successfully picked the lock.
	constexpr int PLAYER_CHARMED                 = 1461; //You lose control of yourself!
	constexpr int TRADER_BUSY                    = 1468; //That Trader is currently with a customer. Please wait until their transaction is finished.
	constexpr int SENSE_CORPSE_DIRECTION         = 1563; //You sense a corpse in this direction.
	constexpr int DUPE_LORE_MERCHANT             = 1573; //%1 tells you, 'You already have the lore item, %2, on your person, on your shroud, in the bank, in a real estate, or as an augment in another item.  You cannot have more than one of a particular lore item at a time.'
	constexpr int QUEUED_TELL                    = 2458; //[queued]
	constexpr int QUEUE_TELL_FULL                = 2459; //[zoing and queue is full]
	constexpr int TRADER_BUSY_TWO                = 3192; //Sorry, that action cannot be performed while trading.
	constexpr int SUSPEND_MINION_UNSUSPEND       = 3267; //%1 tells you, 'I live again...'
	constexpr int SUSPEND_MINION_SUSPEND         = 3268; //%1 tells you, 'By your command, master.'
	constexpr int ONLY_SUMMONED_PETS             = 3269; //3269 This effect only works with summoned pets.
	constexpr int SUSPEND_MINION_FIGHTING        = 3270; //Your pet must be at peace, first.
	constexpr int SHIELD_TARGET_NPC              = 3278; //You must first target a living Player Character.
	constexpr int ALREADY_SHIELDED               = 3279; //Either you or your target is already being shielded.
	constexpr int ALREADY_SHIELDING              = 3280; //Either you or your target is already shielding another.
	constexpr int START_SHIELDING                = 3281; //%1 begins to use %2 as a living shield!
	constexpr int END_SHIELDING                  = 3282; //%1 ceases protecting %2.
	constexpr int OVER_AA_CAP                    = 3374; //Warning: You are currently over the earned Advancement point limit of %1. Please spend some of your stored AA points. The NEXT time you zone all of your AA points over %2 will be deleted. You MUST spend the extra points now.
	constexpr int TRADESKILL_MISSING_ITEM        = 3455; //You are missing a %1.
	constexpr int TRADESKILL_MISSING_COMPONENTS  = 3456; //Sorry, but you don't have everything you need for this recipe in your general inventory.
	constexpr int TRADESKILL_LEARN_RECIPE        = 3457; //You have learned the recipe %1!
	constexpr int TASK_UPDATED                   = 3471; //Your task '%1' has been updated.
	constexpr int YOU_ASSIGNED_TASK              = 3472; //You have been assigned the task '%1'.
	constexpr int DZ_YOU_BELONG                  = 3500; //You cannot create this expedition since you already belong to another.
	constexpr int DZ_REPLAY_YOU                  = 3501; //You cannot create this expedition for another %1d:%2h:%3m since you have recently played here.
	constexpr int DZ_PLAYER_COUNT                = 3503; //You do not meet the player count requirement.  You have %1 players.  You must have at least %2 and no more than %3.
	constexpr int DZ_REPLAY_OTHER                = 3504; //%1 cannot be added to this expedition for another %2D:%3H:%4M since they have recently played in this area.
	constexpr int DZ_AVAILABLE                   = 3507; //%1 is now available to you.
	constexpr int DZADD_INVITE                   = 3508; //Sending an invitation to: %1.
	constexpr int DZ_PREVENT_ENTERING            = 3510; //A strange magical presence prevents you from entering.  It's too dangerous to enter at the moment.
	constexpr int DZADD_INVITE_FAIL              = 3511; //%1 could not be invited to join you.
	constexpr int DZ_NO_LEADER_INFO              = 3512; //Unable to retrieve information on the leader to check permissions.
	constexpr int DZ_NOT_LEADER                  = 3513; //You are not the expedition leader, only %1 can issue this command.
	constexpr int DZ_NOT_MEMBER                  = 3514; //%1 is not a member of this expedition.
	constexpr int DZ_REMOVED                     = 3516; //%1 has been removed from %2.
	constexpr int DZSWAP_INVITE                  = 3517; //Sending an invitation to: %1.  They must accept in order to swap party members.
	constexpr int DZ_LEADER_OFFLINE              = 3518; //%1 is not currently online.  You can only transfer leadership to an online member of the expedition you are in.
	constexpr int DZ_TIMER                       = 3519; //You have %1d:%2h:%3m remaining until you may enter %4.
	constexpr int DZ_LEADER_NAME                 = 3520; //%1 has been made the leader for this expedition.
	constexpr int DZ_LEADER_YOU                  = 3521; //You have been made the leader of this expedition.
	constexpr int DZ_INVITE_ACCEPTED             = 3522; //%1 has accepted your offer to join your expedition.
	constexpr int DZ_ADDED                       = 3523; //%1 has been added to %2.
	constexpr int DZ_INVITE_ERROR                = 3524; //%1 accepted your offer to join your expedition but could not due to error(s).
	constexpr int DZ_INVITE_DECLINED             = 3525; //%1 has declined your offer to join your expedition.
	constexpr int DZ_INVITED                     = 3527; //%1 has asked you to join the expedition:  %2.        Would you like to join?
	constexpr int DZ_WAY_IS_BLOCKED              = 3528; //The way is blocked to you.  Perhaps you would be able to enter if there was a reason to come here.
	constexpr int DZ_NO_TIMERS                   = 3529; //You have no outstanding timers.
	constexpr int DZ_MINUTES_REMAIN              = 3551; //You only have %1 minutes remaining before this expedition comes to an end.
	constexpr int DZ_LEADER                      = 3552; //Expedition Leader: %1
	constexpr int DZ_MEMBERS                     = 3553; //Expedition Members: %1
	constexpr int DZ_EVENT_TIMER                 = 3561; //%1 cannot be added to this expedition since they have recently experienced %2.  They must wait another %3D:%4H:%5M until they can experience it again.  They may be added to the expedition later, once %2 has been completed.
	constexpr int LOOT_NOT_ALLOWED               = 3562; //You are not allowed to loot the item: %1.
	constexpr int DZ_UNABLE_RETRIEVE_LEADER      = 3583; //Unable to retrieve dynamic zone leader to check permissions.
	constexpr int DZADD_NOT_ALLOWING             = 3585; //The expedition is not allowing players to be added.
	constexpr int DZADD_NOT_ONLINE               = 3586; //%1 is not currently online.  A player needs to be online to be added to a Dynamic Zone
	constexpr int DZADD_EXCEED_MAX               = 3587; //You can not add another player since you currently have the maximum number of players allowed (%1) in this zone.
	constexpr int DZADD_ALREADY_PART             = 3588; //You can not add %1 since they are already part of this zone.
	constexpr int DZADD_LEAVE_ZONE               = 3589; //You can not add %1 since they first need to leave the zone before being allowed back in.
	constexpr int DZADD_ALREADY_OTHER            = 3590; //%1 can not be added to this dynamic zone since they are already assigned to another dynamic zone.
	constexpr int DZADD_REPLAY_TIMER             = 3591; //%1 can not be added to this dynamic zone for another %2D:%3H:%4M since they have recently played this zone.
	constexpr int DZADD_EVENT_TIMER              = 3592; //%1 can not be added to this dynamic zone since they have recently experienced %2.  They must wait for another %3D:%4H:%5M, or until event %2 has occurred.
	constexpr int DZADD_PENDING                  = 3593; //%1 currently has an outstanding invitation to join this Dynamic Zone.
	constexpr int DZADD_PENDING_OTHER            = 3594; //%1 currently has an outstanding invitation to join another Dynamic Zone.  Players may only have one invitation outstanding.
	constexpr int DZSWAP_CANNOT_REMOVE           = 3595; //%1 can not be removed from this dynamic zone since they are not assigned to it.
	constexpr int NOT_YOUR_TRAP                  = 3671; //You cannot remove this, you are only allowed to remove traps you have set.
	constexpr int NO_CAST_ON_PET                 = 4045; //You cannot cast this spell on your pet.
	constexpr int REWIND_WAIT                    = 4059; //You must wait a bit longer before using the rewind command again.
	constexpr int CORPSEDRAG_LIMIT               = 4061; //You are already dragging as much as you can!
	constexpr int CORPSEDRAG_ALREADY             = 4062; //You are already dragging %1.
	constexpr int CORPSEDRAG_SOMEONE_ELSE        = 4063; //Someone else is dragging %1.
	constexpr int CORPSEDRAG_BEGIN               = 4064; //You begin to drag %1.
	constexpr int CORPSEDRAG_STOPALL             = 4065; //You stop dragging the corpses.
	constexpr int CORPSEDRAG_STOP                = 4066; //You stop dragging the corpse.
	constexpr int SOS_KEEPS_HIDDEN               = 4086; //Your Shroud of Stealth keeps you hidden from watchful eyes.␣␣
	constexpr int DISARM_NO_TARGET               = 4583; //You can't use disarm on that.
	constexpr int TARGET_TOO_CLOSE               = 4602; //You are too close to your target. Get farther away.
	constexpr int WHOALL_NO_RESULTS              = 5029; //There are no players in EverQuest that match those who filters.
	constexpr int TELL_QUEUED_MESSAGE            = 5045; //You told %1 '%T2. %3'
	constexpr int TOLD_NOT_ONLINE                = 5046; //%1 is not online at this time.
	constexpr int RAID_IS_FULL                   = 5048; //The raid is full.
	constexpr int ZONING_NO_EXPANSION            = 5052; //The zone that you are attempting to enter is part of an expansion that you do not yet own.  You may need to return to the Login screen and enter an account key for that expansion.  If you have received this message in error, please /petition or send an email to EQAccounts@soe.sony.com
	constexpr int PETITION_NO_DELETE             = 5053; //You do not have a petition in the queue.
	constexpr int PETITION_DELETED               = 5054; //Your petition was successfully deleted.
	constexpr int ALREADY_IN_RAID                = 5060; //%1 is already in a raid.
	constexpr int ALREADY_IN_YOUR_RAID           = 5077; //%1 is already in your raid.
	constexpr int NOT_IN_YOUR_RAID               = 5082; //%1 is not in your raid.
	constexpr int GAIN_RAIDEXP                   = 5085; //You gained raid experience!
	constexpr int ALREADY_IN_GRP_RAID            = 5088; //% 1 rejects your invite because they are in a raid and you are not in theirs, or they are a raid group leader
	constexpr int DUNGEON_SEALED                 = 5141; //The gateway to the dungeon is sealed off to you.  Perhaps you would be able to enter if you needed to adventure there.
	constexpr int ADVENTURE_COMPLETE             = 5147; //You received %1 points for successfully completing the adventure.
	constexpr int SUCCOR_FAIL                    = 5169; //The portal collapes before you can escape!
	constexpr int PARCEL_STATUS_2                = 5433; //You currently have % 1 parcels in your mail and are % 2 parcels over the limit of % 3!If you do not retrieve at least % 2 parcels before you logout, they will be lost!
	constexpr int PARCEL_STATUS_1                = 5434; //You currently have % 1 parcels in your mail and are 1 parcel over the limit of % 2!If you do not retrieve at least 1 parcel before you logout, it will be lost!
	constexpr int NO_PROPER_ACCESS               = 5410; //You don't have the proper access rights.
	constexpr int AUGMENT_RESTRICTED             = 5480; //The item does not satisfy the augment's restrictions.
	constexpr int PET_ATTACKING                  = 5501; //%1 tells you, 'Attacking %2 Master.'
	constexpr int AVOID_STUNNING_BLOW            = 5753; //You avoid the stunning blow.
	constexpr int FATAL_BOW_SHOT                 = 5745; //%1 performs a FATAL BOW SHOT!!
	constexpr int SUSPECT_SEES_YOU               = 5746; //You suspect that this being can see you.
	constexpr int MELEE_SILENCE                  = 5806; //You *CANNOT* use this melee ability, you are suffering from amnesia!
	constexpr int DISCIPLINE_REUSE_MSG           = 5807; //You can use the ability %1 again in %2 hour(s) %3 minute(s) %4 seconds.
	constexpr int DISCIPLINE_REUSE_MSG2          = 5808; //You can use the ability %1 again in %2 minute(s) %3 seconds.
	constexpr int FAILED_TAUNT                   = 5811; //You have failed to taunt your target.
	constexpr int PHYSICAL_RESIST_FAIL           = 5817; //Your target avoided your %1 ability.
	constexpr int AA_NO_TARGET                   = 5825; //You must first select a target for this ability!
	constexpr int YOU_RECEIVE                    = 5941; //You receive %1.
	constexpr int NO_TASK_OFFERS                 = 6009; //Sorry %3, I don't have anything for someone with your abilities.
	constexpr int MAX_ACTIVE_TASKS               = 6010; //Sorry %3, you already have the maximum number of active tasks.
	constexpr int TASK_REQUEST_COOLDOWN_TIMER    = 6011; //Sorry, %3, but you can't request another task for %4 minutes and %5 seconds.
	constexpr int FORAGE_MASTERY                 = 6012; //Your forage mastery has enabled you to find something else!
	constexpr int BUYER_WELCOME                  = 6065; //There are %1 Buyers waiting to purchase your loot.  Type /barter to search for them, or use /buyer to set up your own Buy Lines.
	constexpr int BUYER_GREETING                 = 6070; //%1 greets you, '%2'
	constexpr int GUILD_BANK_CANNOT_DEPOSIT      = 6097; // Cannot deposit this item. Containers must be empty, and only one of each LORE and no NO TRADE or TEMPORARY items may be deposited.
	constexpr int GUILD_BANK_FULL                = 6098; // There is no more room in the Guild Bank.
	constexpr int GUILD_BANK_TRANSFERRED         = 6100; // '%1' transferred to Guild Bank from Deposits.
	constexpr int GUILD_BANK_EMPTY_HANDS         = 6108; // You must empty your hands to withdraw from the Guild Bank.
	constexpr int EVOLVE_ITEM_EVOLVED            = 6145; //Your %1 has evolved!
	constexpr int EVOLVE_DETAILS                 = 6146; //Evolving: Level %1/%2 %3%% %4
	constexpr int EVOLVE_LEVEL_LIMIT             = 6147; //Your %1 can not evolve until you reach level %2.
	constexpr int EVOLVE_XP_TXFR_CONFIRM         = 6148; //Are you sure you want to transfer experience between these two items?
	constexpr int EVOLVE_XP_TXFRD                = 6149; //Your item's experience has been transferred!
	constexpr int TRADESKILL_COMBINE_LORE        = 6199; // Combine would result in a LORE item (%1) you already possess.
	constexpr int TRANSFORM_FAILED               = 6326; //This mold cannot be applied to your %1.
	constexpr int TRANSFORM_COMPLETE             = 6327; //You have successfully transformed your %1.
	constexpr int DETRANSFORM_FAILED             = 6341; //%1 has no transformation that can be removed.
	constexpr int GUILD_PERMISSION_FAILED        = 6418; //You do not have permission to change access options.
	constexpr int PARCEL_DELIVERY_ARRIVED        = 6465; //You have received a new parcel delivery!
	constexpr int PARCEL_DELIVERY                = 6466; //%1 tells you, 'I will deliver the %2 to %3 as soon as possible!'
	constexpr int PARCEL_UNKNOWN_NAME            = 6467; //%1 tells you, 'Unfortunately, I don't know anyone by the name of %2. Here is your %3 back.''
	constexpr int PARCEL_DELIVERED               = 6471; //%1 hands you the %2 that was sent from %3.
	constexpr int PARCEL_DELIVERED_2             = 6472; //%1 hands you the stack of %2 %3 that was sent from %4.
	constexpr int GENERIC_STRING                 = 6688; //%1 (used to any basic message)
	constexpr int SENTINEL_TRIG_YOU              = 6724; //You have triggered your sentinel.
	constexpr int SENTINEL_TRIG_OTHER            = 6725; //%1 has triggered your sentinel.
	constexpr int TRADER_MODE_OFF                = 6741; //Bazaar Trader Mode *OFF*
	constexpr int TRADER_MODE_ON                 = 6742; //Bazaar Trader Mode *ON*
	constexpr int TRADER_SET_PRICE               = 6754; //To become a merchant you must assign a price to an item in your list. Do this by selecting an item, then selecting a money amount, and then clicking set price.
	constexpr int IDENTIFY_SPELL                 = 6765; //Item Lore: %1.
	constexpr int PET_NOW_HOLDING                = 6834; //Now holding, Master.  I will not start attacks until ordered.
	constexpr int PET_ON_GHOLD                   = 6843; //Pet greater hold has been set to on.
	constexpr int PET_OFF_GHOLD                  = 6846; //Pet greater hold has been set to off.
	constexpr int PET_GHOLD_ON_MSG               = 6847; //Now greater holding master.  I will only attack something new if ordered.
	constexpr int PET_ON_REGROUPING              = 6854; //Now regrouping, master.
	constexpr int PET_OFF_REGROUPING             = 6855; //No longer regrouping, master.
	constexpr int BUFF_NOT_BLOCKABLE             = 7608; //You cannot block this effect.
	constexpr int LDON_DONT_KNOW_TRAPPED         = 7552; //You do not know if this object is trapped.
	constexpr int LDON_HAVE_DISARMED             = 7553; //You have disarmed %1!
	constexpr int LDON_ACCIDENT_SETOFF           = 7554; //You accidentally set off the trap!
	constexpr int LDON_HAVE_NOT_DISARMED         = 7555; //You have not disarmed %1.
	constexpr int LDON_ACCIDENT_SETOFF2          = 7556; //You accidentally set off the trap!
	constexpr int LDON_CERTAIN_TRAP              = 7557; //You are certain that %1 is trapped.
	constexpr int LDON_CERTAIN_NOT_TRAP          = 7558; //You are certain that %1 is not trapped.
	constexpr int LDON_CANT_DETERMINE_TRAP       = 7559; //You are unable to determine if %1 is trapped.
	constexpr int LDON_PICKLOCK_SUCCESS          = 7560; //You have successfully picked %1!
	constexpr int LDON_PICKLOCK_FAILURE          = 7561; //You have failed to pick %1.
	constexpr int LDON_STILL_LOCKED              = 7562; //You cannot open %1, it is locked.
	constexpr int LDON_BASH_CHEST                = 7563; //%1 try to %2 %3, but do no damage.
	constexpr int DOORS_NO_PICK                  = 7564; //You must have a lock pick in your inventory to do this.
	constexpr int LDON_NO_LOCKPICK               = 7564; //You must have a lock pick in your inventory to do this.
	constexpr int LDON_WAS_NOT_LOCKED            = 7565; //%1 was not locked.
	constexpr int LDON_WAS_NOT_TRAPPED           = 7566; //%1 was not trapped
	constexpr int GAIN_SINGLE_AA_SINGLE_AA       = 8019; //You have gained an ability point!  You now have %1 ability point.
	constexpr int GAIN_SINGLE_AA_MULTI_AA        = 8020; //You have gained an ability point!  You now have %1 ability points.
	constexpr int GAIN_MULTI_AA_MULTI_AA         = 8021; //You have gained %1 ability point(s)!  You now have %2 ability point(s).
	constexpr int GAIN_GROUP_LEADERSHIP_POINT    = 8585; //
	constexpr int GAIN_RAID_LEADERSHIP_POINT     = 8589; //
	constexpr int MAX_GROUP_LEADERSHIP_POINTS    = 8584; //
	constexpr int MAX_RAID_LEADERSHIP_POINTS     = 8591; //
	constexpr int LEADERSHIP_EXP_ON	             = 8653; //
	constexpr int LEADERSHIP_EXP_OFF             = 8654; //
	constexpr int CURRENT_SPELL_EFFECTS          = 8757; //%1's current spell effects:
	constexpr int MAX_MAIN_RAID_ASSISTERS        = 8782; //Max number of main assists reached (3)
	constexpr int MAX_MAIN_RAID_MARKERS          = 8783; //Max number of main markers reached (3)
	constexpr int NOT_DELEGATED_MARKER           = 8794; //You have not been delegated Raid Mark
	constexpr int GAIN_GROUP_LEADERSHIP_EXP      = 8788; //
	constexpr int GAIN_RAID_LEADERSHIP_EXP       = 8789; //
	constexpr int BUFF_MINUTES_REMAINING         = 8799; //%1 (%2 minutes remaining)
	constexpr int RAID_NO_LONGER_MARKED          = 8801; //%1 is no longer marked
	constexpr int YOU_HAVE_BEEN_GIVEN            = 8994; //You have been given: %1
	constexpr int NO_MORE_TRAPS                  = 9002; //You have already placed your maximum number of traps.
	constexpr int FEAR_TOO_HIGH                  = 9035; //Your target is too high of a level for your fear spell.
	constexpr int SLOW_MOSTLY_SUCCESSFUL         = 9029; //Your spell was mostly successful.
	constexpr int SLOW_PARTIALLY_SUCCESSFUL      = 9030; // Your spell was partially successful.
	constexpr int SLOW_SLIGHTLY_SUCCESSFUL       = 9031; //Your spell was slightly successful.
	constexpr int SPELL_OPPOSITE_EFFECT          = 9032; //Your spell may have had the opposite effect of what you desired.
	constexpr int HAS_BEEN_AWAKENED              = 9037; //%1 has been awakened by %2.
	constexpr int YOU_HEAL                       = 9068; //You have healed %1 for %2 points of damage.
	constexpr int YOUR_HIT_DOT                   = 9072; //%1 has taken %2 damage from your %3.
	constexpr int HIT_NON_MELEE                  = 9073; //%1 hit %2 for %3 points of non-melee damage.
	constexpr int GLOWS_BLUE                     = 9074; //Your %1 glows blue.
	constexpr int GLOWS_RED                      = 9075; //Your %1 glows red.
	constexpr int SHAKE_OFF_STUN                 = 9077; //You shake off the stun effect!
	constexpr int STRIKETHROUGH_STRING           = 9078; //You strike through your opponent's defenses!
	constexpr int SPELL_REFLECT                  = 9082; //%1's spell has been reflected by %2.
	constexpr int NO_MORE_AURAS                  = 9160; //You do not have sufficient focus to maintain that ability.
	constexpr int NEW_SPELLS_AVAIL               = 9149; //You have new spells available to you. Check the merchants near your guild master.
	constexpr int FD_CAST_ON_NO_BREAK            = 9174; //The strength of your will allows you to resume feigning death.
	constexpr int SNEAK_RESTRICT                 = 9240; //You can not use this ability because you have not been hidden for long enough.
	constexpr int PET_NOW_FOCUSING               = 9254; //Focusing on one target, Master.
	constexpr int PET_NOT_FOCUSING               = 9263; //No longer focusing on one target, Master.
	constexpr int PET_NOT_CASTING                = 9264; //Not casting spells, Master.
	constexpr int PET_CASTING                    = 9291; //Casting spells normally, Master.
	constexpr int NO_CAST_IN_COMBAT              = 9190; //You can not cast this spell while in combat.
	constexpr int NO_CAST_OUT_OF_COMBAT          = 9191; //You can not cast this spell while out of combat.
	constexpr int NO_ABILITY_IN_COMBAT           = 9192; //You can not use this ability while in combat.
	constexpr int NO_ABILITY_OUT_OF_COMBAT       = 9194; //You can not use this ability while out of combat.
	constexpr int GAIN_GROUPXP_BONUS             = 9298; //You gain party experience (with a bonus)!
	constexpr int GAIN_GROUPXP_PENALTY           = 9301; //You gain party experience (with a penalty)!
	constexpr int GAIN_RAIDXP_BONUS              = 9302; //You gained raid experience (with a bonus)!
	constexpr int GAIN_RAIDXP_PENALTY            = 9303; //You gained raid experience (with a penalty)!
	constexpr int LESSER_SPELL_VERSION           = 11004; //%1 is a lesser version of %2 and cannot be scribed
	constexpr int AE_RAMPAGE                     = 11015; //%1 goes on a WILD RAMPAGE!
	constexpr int GROUP_IS_FULL                  = 12000; //You cannot join that group, it is full.
	constexpr int FACE_ACCEPTED                  = 12028; //Facial features accepted.
	constexpr int TRACKING_BEGIN                 = 12040; //You begin tracking %1.
	constexpr int SPELL_LEVEL_TO_LOW             = 12048; //You will have to achieve level %1 before you can scribe the %2.
	constexpr int YOU_RECEIVE_AS_SPLIT           = 12071; //You receive %1 as your split.
	constexpr int ATTACKFAILED                   = 12158; //%1 try to %2 %3, but %4!
	constexpr int HIT_STRING                     = 12183; //hit
	constexpr int CRUSH_STRING                   = 12191; //crush
	constexpr int PIERCE_STRING                  = 12193; //pierce
	constexpr int KICK_STRING                    = 12195; //kick
	constexpr int STRIKE_STRING                  = 12197; //strike
	constexpr int BACKSTAB_STRING                = 12199; //backstab
	constexpr int BASH_STRING                    = 12201; //bash
	constexpr int GUILD_NOT_MEMBER               = 12242; //You are not a member of any guild.
	constexpr int MEMBER_OF_X_GUILD              = 12256;
	constexpr int OFFICER_OF_X_GUILD             = 12257;
	constexpr int LEADER_OF_X_GUILD              = 12258;
	constexpr int NOT_IN_A_GUILD                 = 12259;
	constexpr int TARGET_PLAYER_FOR_GUILD_STATUS = 12260;
	constexpr int TARGET_ALREADY_IN_GROUP        = 12265; //% 1 is already in another group.
	constexpr int GROUP_INVITEE_NOT_FOUND        = 12268; //You must target a player or use /invite <name> to invite someone to your group.
	constexpr int GROUP_INVITEE_SELF             = 12270; //12270 You cannot invite yourself.
	constexpr int ALREADY_IN_PARTY               = 12272; //That person is already in your party.
	constexpr int TALKING_TO_SELF                = 12323; //Talking to yourself again?
	constexpr int SPLIT_NO_GROUP                 = 12328; //You are not in a group! Keep it all.
	constexpr int NO_LONGER_HIDDEN               = 12337; //You are no longer hidden.
	constexpr int STOP_SNEAKING                  = 12338; //You stop sneaking
	constexpr int NOT_IN_CONTROL                 = 12368; //You do not have control of yourself right now.
	constexpr int NO_SKILL_WHILE_MOUNTED         = 12393; //You can not use this skill while on a mount.
	constexpr int STAND_TO_CAST                  = 12441; //You must be standing to cast a spell.
	constexpr int ALREADY_CASTING                = 12442; //You are already casting a spell!
	constexpr int SHIMMERS_BRIEFLY               = 12444; //Your %1 shimmers briefly.
	constexpr int SENSE_CORPSE_NOT_NAME          = 12446; //You don't sense any corpses of that name.
	constexpr int SENSE_CORPSE_NONE              = 12447; //You don't sense any corpses.
	constexpr int SCREECH_BUFF_BLOCK             = 12448; //Your immunity buff protected you from the spell %1!
	constexpr int NOT_HOLDING_ITEM               = 12452; //You are not holding an item!
	constexpr int SENSE_UNDEAD                   = 12471; //You sense undead in this direction.
	constexpr int SENSE_ANIMAL                   = 12472; //You sense an animal in this direction.
	constexpr int SENSE_SUMMONED                 = 12473; //You sense a summoned being in this direction.
	constexpr int SENSE_NOTHING                  = 12474; //You don't sense anything.
	constexpr int SENSE_TRAP                     = 12475; //You sense a trap in this direction.
	constexpr int LDON_SENSE_TRAP3               = 12476; //You don't sense any traps.
	constexpr int INTERRUPT_SPELL_OTHER          = 12478; //%1's casting is interrupted!
	constexpr int YOU_HIT_NONMELEE               = 12481; //You were hit by non-melee for %1 damage.
	constexpr int TRACK_LOST_TARGET              = 12681; //You have lost your tracking target.
	constexpr int TRACK_STRAIGHT_AHEAD           = 12676;
	constexpr int TRACK_AHEAD_AND_TO             = 12677;
	constexpr int TRACK_TO_THE                   = 12678;
	constexpr int TRACK_BEHIND_AND_TO            = 12679;
	constexpr int TRACK_BEHIND_YOU               = 12680;
	constexpr int BEAM_SMILE                     = 12501; //%1 beams a smile at %2
	constexpr int SONG_ENDS_ABRUPTLY             = 12686; //Your song ends abruptly.
	constexpr int SONG_ENDS                      = 12687; //Your song ends.
	constexpr int SONG_ENDS_OTHER                = 12688; //%1's song ends.
	constexpr int SONG_ENDS_ABRUPTLY_OTHER       = 12689; //%1's song ends abruptly.
	constexpr int DIVINE_AURA_NO_ATK             = 12695; //You can't attack while invulnerable!
	constexpr int TRY_ATTACKING_SOMEONE          = 12696; //Try attacking someone other than yourself, it's more productive
	constexpr int RANGED_TOO_CLOSE               = 12698; //Your target is too close to use a ranged weapon!
	constexpr int BACKSTAB_WEAPON                = 12874; //You need a piercing weapon as your primary weapon in order to backstab
	constexpr int DISARMED                       = 12889; //You have been disarmed!
	constexpr int DISARM_SUCCESS                 = 12890; //You disarmed %1!
	constexpr int DISARM_FAILED                  = 12891; //Your attempt to disarm failed.
	constexpr int MORE_SKILLED_THAN_I            = 12931; //%1 tells you, 'You are more skilled than I! What could I possibly teach you?'
	constexpr int SURNAME_EXISTS                 = 12939; //You already have a surname. Operation failed.
	constexpr int SURNAME_LEVEL                  = 12940; //You can only submit a surname upon reaching the 20th level. Operation failed.
	constexpr int SURNAME_TOO_LONG               = 12942; //Surname must be less than 20 characters in length.
	constexpr int REPORT_ONCE                    = 12945; //You may only submit a report once per time that you zone. Thank you.
	constexpr int NOW_INVISIBLE                  = 12950; //%1 is now Invisible.
	constexpr int NOW_VISIBLE                    = 12951; //%1 is now Visible.
	constexpr int YOU_TAKE_DOT                   = 12954; //You have taken %1 damage from %2 by %3
	constexpr int GUILD_NOT_MEMBER2              = 12966; //You are not in a guild.
	constexpr int HOT_HEAL_SELF                  = 12976; //You have been healed for %1 hit points by your %2.
	constexpr int HOT_HEAL_OTHER                 = 12997; //You have healed %1 for %2 hit points with your %3.
	constexpr int HOT_HEALED_OTHER               = 12998; //%1 healed you for %2 hit points by %3.
	constexpr int DISC_LEVEL_USE_ERROR           = 13004; //You are not sufficient level to use this discipline.
	constexpr int SPLIT_FAIL                     = 13112; //There is not enough to split, keep it.
	constexpr int TOGGLE_ON                      = 13172; //Asking server to turn ON your incoming tells.
	constexpr int TOGGLE_OFF                     = 13173; //Asking server to turn OFF all incoming tells for you.
	constexpr int DUEL_INPROGRESS                = 13251; //You have already accepted a duel with someone else cowardly dog.
	constexpr int OTHER_HIT_DOT                  = 13327; //%1 has taken %2 damage from %3 by %4.
	constexpr int GAIN_XP_BONUS                  = 14541; //You gain experience (with a bonus)!
	constexpr int GAIN_XP_PENALTY                = 14542; //You gain experience (with a penalty)!
	constexpr int GENERIC_MISS                   = 15041; //%1 missed %2
}

#endif

