create table titles (
	id int UNSIGNED primary key AUTO_INCREMENT,
	skill_id tinyint UNSIGNED NOT NULL,
	skill_value mediumint UNSIGNED NOT NULL,
	aa_points TINYINT UNSIGNED NOT NULL,
	title varchar(32) NOT NULL
);

alter table inventory add instnodrop tinyint(1) unsigned default 0 not null;

alter table tributes ADD isguild TINYINT NOT NULL DEFAULT '0';
alter table tributes drop primary key;
alter table tributes ADD primary key(id,isguild);

ALTER TABLE zone ADD fog_red2 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_green2 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_blue2 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_minclip2 float NOT NULL default '450';
ALTER TABLE zone ADD fog_maxclip2 float NOT NULL default '450';
ALTER TABLE zone ADD fog_red3 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_green3 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_blue3 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_minclip3 float NOT NULL default '450';
ALTER TABLE zone ADD fog_maxclip3 float NOT NULL default '450';
ALTER TABLE zone ADD fog_red4 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_green4 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_blue4 tinyint(3) unsigned NOT NULL default '0';
ALTER TABLE zone ADD fog_minclip4 float NOT NULL default '450';
ALTER TABLE zone ADD fog_maxclip4 float NOT NULL default '450';
UPDATE zone SET fog_red2=fog_red,fog_red3=fog_red,fog_red4=fog_red,
fog_green2=fog_green,fog_green3=fog_green,fog_green4=fog_green,
fog_blue2=fog_blue,fog_blue3=fog_blue,fog_blue4=fog_blue,
fog_minclip2=fog_minclip,fog_minclip3=fog_minclip,fog_minclip4=fog_minclip,
fog_maxclip2=fog_maxclip,fog_maxclip3=fog_maxclip,fog_maxclip4=fog_maxclip;

ALTER TABLE zone_points ADD target_zone_id int UNSIGNED NOT NULL;
UPDATE zone_points SET target_zone_id=39 WHERE target_zone='hole';
UPDATE zone_points SET target_zone_id=75 WHERE target_zone='paineel';
UPDATE zone_points SET target_zone_id=100 WHERE target_zone='stonebrunt';
UPDATE zone_points SET target_zone_id=101 WHERE target_zone='warrens';
UPDATE zone_points SET target_zone_id=109 WHERE target_zone='veksar';
UPDATE zone_points SET target_zone_id=181 WHERE target_zone='jaggedpine';
UPDATE zone_points SET target_zone_id=1 WHERE target_zone='qeynos';
UPDATE zone_points SET target_zone_id=2 WHERE target_zone='qeynos2';
UPDATE zone_points SET target_zone_id=3 WHERE target_zone='qrg';
UPDATE zone_points SET target_zone_id=4 WHERE target_zone='qeytoqrg';
UPDATE zone_points SET target_zone_id=5 WHERE target_zone='highpass';
UPDATE zone_points SET target_zone_id=6 WHERE target_zone='highkeep';
UPDATE zone_points SET target_zone_id=8 WHERE target_zone='freportn';
UPDATE zone_points SET target_zone_id=9 WHERE target_zone='freportw';
UPDATE zone_points SET target_zone_id=10 WHERE target_zone='freporte';
UPDATE zone_points SET target_zone_id=11 WHERE target_zone='runnyeye';
UPDATE zone_points SET target_zone_id=12 WHERE target_zone='qey2hh1';
UPDATE zone_points SET target_zone_id=13 WHERE target_zone='northkarana';
UPDATE zone_points SET target_zone_id=14 WHERE target_zone='southkarana';
UPDATE zone_points SET target_zone_id=15 WHERE target_zone='eastkarana';
UPDATE zone_points SET target_zone_id=16 WHERE target_zone='beholder';
UPDATE zone_points SET target_zone_id=17 WHERE target_zone='blackburrow';
UPDATE zone_points SET target_zone_id=18 WHERE target_zone='paw';
UPDATE zone_points SET target_zone_id=19 WHERE target_zone='rivervale';
UPDATE zone_points SET target_zone_id=20 WHERE target_zone='kithicor';
UPDATE zone_points SET target_zone_id=21 WHERE target_zone='commons';
UPDATE zone_points SET target_zone_id=22 WHERE target_zone='ecommons';
UPDATE zone_points SET target_zone_id=23 WHERE target_zone='erudnint';
UPDATE zone_points SET target_zone_id=24 WHERE target_zone='erudnext';
UPDATE zone_points SET target_zone_id=25 WHERE target_zone='nektulos';
UPDATE zone_points SET target_zone_id=26 WHERE target_zone='cshome';
UPDATE zone_points SET target_zone_id=27 WHERE target_zone='lavastorm';
UPDATE zone_points SET target_zone_id=29 WHERE target_zone='halas';
UPDATE zone_points SET target_zone_id=30 WHERE target_zone='everfrost';
UPDATE zone_points SET target_zone_id=31 WHERE target_zone='soldunga';
UPDATE zone_points SET target_zone_id=32 WHERE target_zone='soldungb';
UPDATE zone_points SET target_zone_id=33 WHERE target_zone='misty';
UPDATE zone_points SET target_zone_id=34 WHERE target_zone='nro';
UPDATE zone_points SET target_zone_id=35 WHERE target_zone='sro';
UPDATE zone_points SET target_zone_id=36 WHERE target_zone='befallen';
UPDATE zone_points SET target_zone_id=37 WHERE target_zone='oasis';
UPDATE zone_points SET target_zone_id=38 WHERE target_zone='tox';
UPDATE zone_points SET target_zone_id=40 WHERE target_zone='neriaka';
UPDATE zone_points SET target_zone_id=41 WHERE target_zone='neriakb';
UPDATE zone_points SET target_zone_id=42 WHERE target_zone='neriakc';
UPDATE zone_points SET target_zone_id=44 WHERE target_zone='najena';
UPDATE zone_points SET target_zone_id=46 WHERE target_zone='innothule';
UPDATE zone_points SET target_zone_id=47 WHERE target_zone='feerrott';
UPDATE zone_points SET target_zone_id=48 WHERE target_zone='cazicthule';
UPDATE zone_points SET target_zone_id=49 WHERE target_zone='oggok';
UPDATE zone_points SET target_zone_id=50 WHERE target_zone='rathemtn';
UPDATE zone_points SET target_zone_id=51 WHERE target_zone='lakerathe';
UPDATE zone_points SET target_zone_id=52 WHERE target_zone='gukta';
UPDATE zone_points SET target_zone_id=54 WHERE target_zone='gfaydark';
UPDATE zone_points SET target_zone_id=55 WHERE target_zone='akanon';
UPDATE zone_points SET target_zone_id=56 WHERE target_zone='steamfont';
UPDATE zone_points SET target_zone_id=57 WHERE target_zone='lfaydark';
UPDATE zone_points SET target_zone_id=58 WHERE target_zone='crushbone';
UPDATE zone_points SET target_zone_id=59 WHERE target_zone='mistmoore';
UPDATE zone_points SET target_zone_id=60 WHERE target_zone='kaladima';
UPDATE zone_points SET target_zone_id=61 WHERE target_zone='felwithea';
UPDATE zone_points SET target_zone_id=62 WHERE target_zone='felwitheb';
UPDATE zone_points SET target_zone_id=63 WHERE target_zone='unrest';
UPDATE zone_points SET target_zone_id=64 WHERE target_zone='kedge';
UPDATE zone_points SET target_zone_id=65 WHERE target_zone='guktop';
UPDATE zone_points SET target_zone_id=66 WHERE target_zone='gukbottom';
UPDATE zone_points SET target_zone_id=67 WHERE target_zone='kaladimb';
UPDATE zone_points SET target_zone_id=68 WHERE target_zone='butcher';
UPDATE zone_points SET target_zone_id=69 WHERE target_zone='oot';
UPDATE zone_points SET target_zone_id=70 WHERE target_zone='cauldron';
UPDATE zone_points SET target_zone_id=71 WHERE target_zone='airplane';
UPDATE zone_points SET target_zone_id=72 WHERE target_zone='fearplane';
UPDATE zone_points SET target_zone_id=73 WHERE target_zone='permafrost';
UPDATE zone_points SET target_zone_id=74 WHERE target_zone='kerraridge';
UPDATE zone_points SET target_zone_id=76 WHERE target_zone='hateplane';
UPDATE zone_points SET target_zone_id=77 WHERE target_zone='arena';
UPDATE zone_points SET target_zone_id=180 WHERE target_zone='arena2';
UPDATE zone_points SET target_zone_id=98 WHERE target_zone='erudsxing';
UPDATE zone_points SET target_zone_id=45 WHERE target_zone='qcat';
UPDATE zone_points SET target_zone_id=78 WHERE target_zone='fieldofbone';
UPDATE zone_points SET target_zone_id=79 WHERE target_zone='warslikswood';
UPDATE zone_points SET target_zone_id=80 WHERE target_zone='soltemple';
UPDATE zone_points SET target_zone_id=81 WHERE target_zone='droga';
UPDATE zone_points SET target_zone_id=82 WHERE target_zone='cabwest';
UPDATE zone_points SET target_zone_id=83 WHERE target_zone='swampofnohope';
UPDATE zone_points SET target_zone_id=84 WHERE target_zone='firiona';
UPDATE zone_points SET target_zone_id=85 WHERE target_zone='lakeofillomen';
UPDATE zone_points SET target_zone_id=86 WHERE target_zone='dreadlands';
UPDATE zone_points SET target_zone_id=87 WHERE target_zone='burningwood';
UPDATE zone_points SET target_zone_id=88 WHERE target_zone='kaesora';
UPDATE zone_points SET target_zone_id=89 WHERE target_zone='sebilis';
UPDATE zone_points SET target_zone_id=90 WHERE target_zone='citymist';
UPDATE zone_points SET target_zone_id=91 WHERE target_zone='skyfire';
UPDATE zone_points SET target_zone_id=92 WHERE target_zone='frontiermtns';
UPDATE zone_points SET target_zone_id=93 WHERE target_zone='overthere';
UPDATE zone_points SET target_zone_id=94 WHERE target_zone='emeraldjungle';
UPDATE zone_points SET target_zone_id=95 WHERE target_zone='trakanon';
UPDATE zone_points SET target_zone_id=96 WHERE target_zone='timorous';
UPDATE zone_points SET target_zone_id=97 WHERE target_zone='kurn';
UPDATE zone_points SET target_zone_id=102 WHERE target_zone='karnor';
UPDATE zone_points SET target_zone_id=103 WHERE target_zone='chardok';
UPDATE zone_points SET target_zone_id=104 WHERE target_zone='dalnir';
UPDATE zone_points SET target_zone_id=105 WHERE target_zone='charasis';
UPDATE zone_points SET target_zone_id=106 WHERE target_zone='cabeast';
UPDATE zone_points SET target_zone_id=107 WHERE target_zone='nurga';
UPDATE zone_points SET target_zone_id=108 WHERE target_zone='veeshan';
UPDATE zone_points SET target_zone_id=186 WHERE target_zone='hateplaneb';
UPDATE zone_points SET target_zone_id=188 WHERE target_zone='tutoriala';
UPDATE zone_points SET target_zone_id=189 WHERE target_zone='tutorialb';
UPDATE zone_points SET target_zone_id=110 WHERE target_zone='iceclad';
UPDATE zone_points SET target_zone_id=111 WHERE target_zone='frozenshadow';
UPDATE zone_points SET target_zone_id=112 WHERE target_zone='velketor';
UPDATE zone_points SET target_zone_id=113 WHERE target_zone='kael';
UPDATE zone_points SET target_zone_id=114 WHERE target_zone='skyshrine';
UPDATE zone_points SET target_zone_id=115 WHERE target_zone='thurgadina';
UPDATE zone_points SET target_zone_id=116 WHERE target_zone='eastwastes';
UPDATE zone_points SET target_zone_id=117 WHERE target_zone='cobaltscar';
UPDATE zone_points SET target_zone_id=118 WHERE target_zone='greatdivide';
UPDATE zone_points SET target_zone_id=119 WHERE target_zone='wakening';
UPDATE zone_points SET target_zone_id=120 WHERE target_zone='westwastes';
UPDATE zone_points SET target_zone_id=121 WHERE target_zone='crystal';
UPDATE zone_points SET target_zone_id=123 WHERE target_zone='necropolis';
UPDATE zone_points SET target_zone_id=124 WHERE target_zone='templeveeshan';
UPDATE zone_points SET target_zone_id=125 WHERE target_zone='sirens';
UPDATE zone_points SET target_zone_id=126 WHERE target_zone='mischiefplane';
UPDATE zone_points SET target_zone_id=127 WHERE target_zone='growthplane';
UPDATE zone_points SET target_zone_id=128 WHERE target_zone='sleeper';
UPDATE zone_points SET target_zone_id=129 WHERE target_zone='thurgadinb';
UPDATE zone_points SET target_zone_id=183 WHERE target_zone='tutorial';
UPDATE zone_points SET target_zone_id=184 WHERE target_zone='load';
UPDATE zone_points SET target_zone_id=185 WHERE target_zone='load2';
UPDATE zone_points SET target_zone_id=150 WHERE target_zone='Shadowhaven';
UPDATE zone_points SET target_zone_id=151 WHERE target_zone='Bazaar';
UPDATE zone_points SET target_zone_id=152 WHERE target_zone='Nexus';
UPDATE zone_points SET target_zone_id=153 WHERE target_zone='echo';
UPDATE zone_points SET target_zone_id=154 WHERE target_zone='acrylia';
UPDATE zone_points SET target_zone_id=155 WHERE target_zone='sharvahl';
UPDATE zone_points SET target_zone_id=156 WHERE target_zone='paludal';
UPDATE zone_points SET target_zone_id=157 WHERE target_zone='fungusgrove';
UPDATE zone_points SET target_zone_id=158 WHERE target_zone='vexthal';
UPDATE zone_points SET target_zone_id=159 WHERE target_zone='sseru';
UPDATE zone_points SET target_zone_id=160 WHERE target_zone='katta';
UPDATE zone_points SET target_zone_id=161 WHERE target_zone='netherbian';
UPDATE zone_points SET target_zone_id=162 WHERE target_zone='ssratemple';
UPDATE zone_points SET target_zone_id=163 WHERE target_zone='griegsend';
UPDATE zone_points SET target_zone_id=164 WHERE target_zone='thedeep';
UPDATE zone_points SET target_zone_id=165 WHERE target_zone='shadeweaver';
UPDATE zone_points SET target_zone_id=166 WHERE target_zone='hollowshade';
UPDATE zone_points SET target_zone_id=167 WHERE target_zone='grimling';
UPDATE zone_points SET target_zone_id=168 WHERE target_zone='mseru';
UPDATE zone_points SET target_zone_id=169 WHERE target_zone='letalis';
UPDATE zone_points SET target_zone_id=170 WHERE target_zone='twilight';
UPDATE zone_points SET target_zone_id=171 WHERE target_zone='thegrey';
UPDATE zone_points SET target_zone_id=172 WHERE target_zone='tenebrous';
UPDATE zone_points SET target_zone_id=173 WHERE target_zone='maiden';
UPDATE zone_points SET target_zone_id=174 WHERE target_zone='dawnshroud';
UPDATE zone_points SET target_zone_id=175 WHERE target_zone='scarlet';
UPDATE zone_points SET target_zone_id=176 WHERE target_zone='umbral';
UPDATE zone_points SET target_zone_id=179 WHERE target_zone='akheva';
UPDATE zone_points SET target_zone_id=995 WHERE target_zone='arttest';
UPDATE zone_points SET target_zone_id=200 WHERE target_zone='codecay';
UPDATE zone_points SET target_zone_id=201 WHERE target_zone='pojustice';
UPDATE zone_points SET target_zone_id=202 WHERE target_zone='poknowledge';
UPDATE zone_points SET target_zone_id=203 WHERE target_zone='potranquility';
UPDATE zone_points SET target_zone_id=204 WHERE target_zone='ponightmare';
UPDATE zone_points SET target_zone_id=205 WHERE target_zone='podisease';
UPDATE zone_points SET target_zone_id=206 WHERE target_zone='poinnovation';
UPDATE zone_points SET target_zone_id=207 WHERE target_zone='potorment';
UPDATE zone_points SET target_zone_id=208 WHERE target_zone='povalor';
UPDATE zone_points SET target_zone_id=209 WHERE target_zone='bothunder';
UPDATE zone_points SET target_zone_id=210 WHERE target_zone='postorms';
UPDATE zone_points SET target_zone_id=211 WHERE target_zone='hohonora';
UPDATE zone_points SET target_zone_id=212 WHERE target_zone='solrotower';
UPDATE zone_points SET target_zone_id=213 WHERE target_zone='powar';
UPDATE zone_points SET target_zone_id=214 WHERE target_zone='potactics';
UPDATE zone_points SET target_zone_id=215 WHERE target_zone='poair';
UPDATE zone_points SET target_zone_id=216 WHERE target_zone='powater';
UPDATE zone_points SET target_zone_id=217 WHERE target_zone='pofire';
UPDATE zone_points SET target_zone_id=218 WHERE target_zone='poeartha';
UPDATE zone_points SET target_zone_id=219 WHERE target_zone='potimea';
UPDATE zone_points SET target_zone_id=220 WHERE target_zone='hohonorb';
UPDATE zone_points SET target_zone_id=221 WHERE target_zone='nightmareb';
UPDATE zone_points SET target_zone_id=222 WHERE target_zone='poearthb';
UPDATE zone_points SET target_zone_id=223 WHERE target_zone='potimeb';
UPDATE zone_points SET target_zone_id=224 WHERE target_zone='gunthak';
UPDATE zone_points SET target_zone_id=225 WHERE target_zone='dulak';
UPDATE zone_points SET target_zone_id=226 WHERE target_zone='torgiran';
UPDATE zone_points SET target_zone_id=227 WHERE target_zone='nadox';
UPDATE zone_points SET target_zone_id=228 WHERE target_zone='hatesfury';
UPDATE zone_points SET target_zone_id=277 WHERE target_zone='chardokb';
UPDATE zone_points SET target_zone_id=278 WHERE target_zone='soldungc';
UPDATE zone_points SET target_zone_id=229 WHERE target_zone='guka';
UPDATE zone_points SET target_zone_id=234 WHERE target_zone='gukb';
UPDATE zone_points SET target_zone_id=239 WHERE target_zone='gukc';
UPDATE zone_points SET target_zone_id=244 WHERE target_zone='gukd';
UPDATE zone_points SET target_zone_id=249 WHERE target_zone='guke';
UPDATE zone_points SET target_zone_id=254 WHERE target_zone='gukf';
UPDATE zone_points SET target_zone_id=259 WHERE target_zone='gukg';
UPDATE zone_points SET target_zone_id=264 WHERE target_zone='gukh';
UPDATE zone_points SET target_zone_id=232 WHERE target_zone='mira';
UPDATE zone_points SET target_zone_id=237 WHERE target_zone='mirb';
UPDATE zone_points SET target_zone_id=242 WHERE target_zone='mirc';
UPDATE zone_points SET target_zone_id=247 WHERE target_zone='mird';
UPDATE zone_points SET target_zone_id=252 WHERE target_zone='mire';
UPDATE zone_points SET target_zone_id=257 WHERE target_zone='mirf';
UPDATE zone_points SET target_zone_id=262 WHERE target_zone='mirg';
UPDATE zone_points SET target_zone_id=267 WHERE target_zone='mirh';
UPDATE zone_points SET target_zone_id=271 WHERE target_zone='miri';
UPDATE zone_points SET target_zone_id=275 WHERE target_zone='mirj';
UPDATE zone_points SET target_zone_id=233 WHERE target_zone='mmca';
UPDATE zone_points SET target_zone_id=238 WHERE target_zone='mmcb';
UPDATE zone_points SET target_zone_id=243 WHERE target_zone='mmcc';
UPDATE zone_points SET target_zone_id=248 WHERE target_zone='mmcd';
UPDATE zone_points SET target_zone_id=253 WHERE target_zone='mmce';
UPDATE zone_points SET target_zone_id=258 WHERE target_zone='mmcf';
UPDATE zone_points SET target_zone_id=263 WHERE target_zone='mmcg';
UPDATE zone_points SET target_zone_id=268 WHERE target_zone='mmch';
UPDATE zone_points SET target_zone_id=272 WHERE target_zone='mmci';
UPDATE zone_points SET target_zone_id=276 WHERE target_zone='mmcj';
UPDATE zone_points SET target_zone_id=230 WHERE target_zone='ruja';
UPDATE zone_points SET target_zone_id=235 WHERE target_zone='rujb';
UPDATE zone_points SET target_zone_id=240 WHERE target_zone='rujc';
UPDATE zone_points SET target_zone_id=245 WHERE target_zone='rujd';
UPDATE zone_points SET target_zone_id=250 WHERE target_zone='ruje';
UPDATE zone_points SET target_zone_id=255 WHERE target_zone='rujf';
UPDATE zone_points SET target_zone_id=260 WHERE target_zone='rujg';
UPDATE zone_points SET target_zone_id=265 WHERE target_zone='rujh';
UPDATE zone_points SET target_zone_id=269 WHERE target_zone='ruji';
UPDATE zone_points SET target_zone_id=273 WHERE target_zone='rujj';
UPDATE zone_points SET target_zone_id=231 WHERE target_zone='taka';
UPDATE zone_points SET target_zone_id=236 WHERE target_zone='takb';
UPDATE zone_points SET target_zone_id=241 WHERE target_zone='takc';
UPDATE zone_points SET target_zone_id=246 WHERE target_zone='takd';
UPDATE zone_points SET target_zone_id=251 WHERE target_zone='take';
UPDATE zone_points SET target_zone_id=256 WHERE target_zone='takf';
UPDATE zone_points SET target_zone_id=261 WHERE target_zone='takg';
UPDATE zone_points SET target_zone_id=266 WHERE target_zone='takh';
UPDATE zone_points SET target_zone_id=270 WHERE target_zone='taki';
UPDATE zone_points SET target_zone_id=274 WHERE target_zone='takj';
UPDATE zone_points SET target_zone_id=187 WHERE target_zone='shadowrest';
UPDATE zone_points SET target_zone_id=279 WHERE target_zone='abysmal';
UPDATE zone_points SET target_zone_id=280 WHERE target_zone='natimbi';
UPDATE zone_points SET target_zone_id=281 WHERE target_zone='qinimi';
UPDATE zone_points SET target_zone_id=282 WHERE target_zone='riwwi';
UPDATE zone_points SET target_zone_id=283 WHERE target_zone='barindu';
UPDATE zone_points SET target_zone_id=284 WHERE target_zone='ferubi';
UPDATE zone_points SET target_zone_id=285 WHERE target_zone='snpool';
UPDATE zone_points SET target_zone_id=286 WHERE target_zone='snlair';
UPDATE zone_points SET target_zone_id=287 WHERE target_zone='snplant';
UPDATE zone_points SET target_zone_id=288 WHERE target_zone='sncrematory';
UPDATE zone_points SET target_zone_id=289 WHERE target_zone='tipt';
UPDATE zone_points SET target_zone_id=290 WHERE target_zone='vxed';
UPDATE zone_points SET target_zone_id=291 WHERE target_zone='yxtta';
UPDATE zone_points SET target_zone_id=292 WHERE target_zone='uqua';
UPDATE zone_points SET target_zone_id=293 WHERE target_zone='kodtaz';
UPDATE zone_points SET target_zone_id=294 WHERE target_zone='ikkinz';
UPDATE zone_points SET target_zone_id=295 WHERE target_zone='inktuta';
UPDATE zone_points SET target_zone_id=296 WHERE target_zone='txevu';
UPDATE zone_points SET target_zone_id=297 WHERE target_zone='tacvi';
UPDATE zone_points SET target_zone_id=298 WHERE target_zone='qvic';
UPDATE zone_points SET target_zone_id=299 WHERE target_zone='qvicb';
UPDATE zone_points SET target_zone_id=182 WHERE target_zone='nedaria';
UPDATE zone_points SET target_zone_id=300 WHERE target_zone='wallofslaughter';
UPDATE zone_points SET target_zone_id=301 WHERE target_zone='bloodfields';
UPDATE zone_points SET target_zone_id=302 WHERE target_zone='draniksscar';
UPDATE zone_points SET target_zone_id=303 WHERE target_zone='causeway';
UPDATE zone_points SET target_zone_id=304 WHERE target_zone='chambersa';
UPDATE zone_points SET target_zone_id=305 WHERE target_zone='chambersb';
UPDATE zone_points SET target_zone_id=306 WHERE target_zone='chambersc';
UPDATE zone_points SET target_zone_id=307 WHERE target_zone='chambersd';
UPDATE zone_points SET target_zone_id=308 WHERE target_zone='chamberse';
UPDATE zone_points SET target_zone_id=309 WHERE target_zone='chambersf';
UPDATE zone_points SET target_zone_id=316 WHERE target_zone='provinggrounds';
UPDATE zone_points SET target_zone_id=317 WHERE target_zone='anguish';
UPDATE zone_points SET target_zone_id=318 WHERE target_zone='dranikhollowsa';
UPDATE zone_points SET target_zone_id=319 WHERE target_zone='dranikhollowsb';
UPDATE zone_points SET target_zone_id=320 WHERE target_zone='dranikhollowsc';
UPDATE zone_points SET target_zone_id=328 WHERE target_zone='dranikcatacombsa';
UPDATE zone_points SET target_zone_id=329 WHERE target_zone='dranikcatacombsb';
UPDATE zone_points SET target_zone_id=330 WHERE target_zone='dranikcatacombsc';
UPDATE zone_points SET target_zone_id=331 WHERE target_zone='draniksewersa';
UPDATE zone_points SET target_zone_id=332 WHERE target_zone='draniksewersb';
UPDATE zone_points SET target_zone_id=333 WHERE target_zone='draniksewersc';
UPDATE zone_points SET target_zone_id=334 WHERE target_zone='riftseekers';
UPDATE zone_points SET target_zone_id=335 WHERE target_zone='harbingers';
UPDATE zone_points SET target_zone_id=336 WHERE target_zone='dranik';
ALTER TABLE zone_points DROP target_zone;

ALTER TABLE account ADD hideme TINYINT NOT NULL DEFAULT 0;

ALTER TABLE `character_` ADD `extprofile` BLOB NOT NULL;

