alter table items change unknown021 UNK012 int NOT NULL DEFAULT '0';
alter table items change unknown022 UNK013 int NOT NULL DEFAULT '0';
alter table items change unknown023 benefitflag int NOT NULL DEFAULT '0';
alter table items change unknown064 UNK054 int NOT NULL DEFAULT '0';
alter table items change unknown070 UNK059 int NOT NULL DEFAULT '0';
alter table items change unknown072 UNK061 int NOT NULL DEFAULT '0';
alter table items change combatskill extradmgskill int NOT NULL DEFAULT '0';
alter table items change combatskilldmg extradmgamt int NOT NULL DEFAULT '0';
alter table items change booktype book int NOT NULL DEFAULT '0';
alter table items change unknown108 booktype int NOT NULL DEFAULT '0';
alter table items change banedmgamt2 banedmgraceamt int NOT NULL DEFAULT '0';
alter table items change augmentrestriction augrestrict int NOT NULL DEFAULT '0';
alter table items change tribute favor int NOT NULL DEFAULT '0';
alter table items change attackbonus attack int NOT NULL DEFAULT '0';
alter table items change hpregen regen int NOT NULL DEFAULT '0';
alter table items change hastepercent haste int NOT NULL DEFAULT '0';
alter table items change unknown125 recastdelay int NOT NULL DEFAULT '0';
alter table items change unknown126 recasttype int NOT NULL DEFAULT '0';
alter table items change unknown127 guildfavor int NOT NULL DEFAULT '0';
alter table items change distiller augdistiller int NOT NULL DEFAULT '0';
alter table items change unknown129 UNK117 int NOT NULL DEFAULT '0';
alter table items change unknown130 UNK118 int NOT NULL DEFAULT '0';
alter table items change attuneable old_attuneable int NOT NULL DEFAULT '0';
alter table items change unknown131 attuneable int NOT NULL DEFAULT '0';
alter table items change unknown132 nopet int NOT NULL DEFAULT '0';
alter table items add UNK121  int NOT NULL DEFAULT '0';
alter table items add pointtype  int NOT NULL DEFAULT '0';
alter table items add potionbelt  int NOT NULL DEFAULT '0';
alter table items add UNK124  int NOT NULL DEFAULT '0';
alter table items add stacksize  int NOT NULL DEFAULT '0';
alter table items change hasteproclvl level int NOT NULL DEFAULT '0';
alter table items change spellid clickeffect int NOT NULL DEFAULT '0';
alter table items change focusid focuseffect int NOT NULL DEFAULT '0';
alter table items change effecttype clicktype int NOT NULL DEFAULT '0';
alter table items change level clicklevel int NOT NULL DEFAULT '0';
alter table items add UNK129 int NOT NULL DEFAULT '0';
alter table items add proceffect int NOT NULL DEFAULT '0';
alter table items add proctype int NOT NULL DEFAULT '0';
alter table items add proclevel int NOT NULL DEFAULT '0';
alter table items add UNK133 int NOT NULL DEFAULT '0';
alter table items add worneffect int NOT NULL DEFAULT '0';
alter table items add worntype int NOT NULL DEFAULT '0';
alter table items add wornlevel int NOT NULL DEFAULT '0';
alter table items add UNK137 int NOT NULL DEFAULT '0';
alter table items add focustype int NOT NULL DEFAULT '0';
alter table items add focuslevel int NOT NULL DEFAULT '0';
alter table items add UNK141 int NOT NULL DEFAULT '0';
alter table items add scrolleffect int NOT NULL DEFAULT '0';
alter table items add scrolltype int NOT NULL DEFAULT '0';
alter table items add scrolllevel int NOT NULL DEFAULT '0';
alter table items add UNK145 int NOT NULL DEFAULT '0';
alter table items change cost price int NOT NULL DEFAULT '0';
alter table items change casttime2 casttime_ int NOT NULL DEFAULT '0';
alter table items change proc_rate_mod procrate int NOT NULL DEFAULT '0';
alter table items change charmformula charmfileid  varchar(32) NOT NULL DEFAULT '';
alter table items modify filename varchar(32) NOT NULL DEFAULT '';
alter table items change ldonpointtheme ldontheme int NOT NULL DEFAULT '0';
alter table items change ldonpointcost ldonprice int NOT NULL DEFAULT '0';
alter table items change gmflag fvnodrop int NOT NULL DEFAULT '0';
alter table items add serialized datetime;
alter table items add verified datetime;
alter table items add serialization text;
alter table items add source varchar(20) NOT NULL;

alter table items add UNK033 int NOT NULL DEFAULT '0';

alter table items drop column charges;
alter table items drop column unknown001;
alter table items drop column collected_slot_id;
alter table items drop column merchantprice;
alter table items drop column unknown004;
alter table items drop column collected_inst_id;
alter table items drop column unknown006;
alter table items drop column spellcharges;
alter table items drop column old_attuneable;

update items set proctype=clicktype,proceffect=clickeffect,proclevel=clicklevel,clicktype=0,clickeffect=0,clicklevel=0 where clickeffect>0 and clicktype =0;
update items set worntype=clicktype,proceffect=clickeffect,proclevel=clicklevel,clicktype=0,clickeffect=0,clicklevel=0 where clickeffect>0 and clicktype =2;
update items set focustype=6 where focuseffect>0;
update items set scrolltype=7,scrolleffect=clickeffect,scrolllevel=clicklevel,clicktype=0,clickeffect=0,clicklevel=0 where clickeffect>0 and itemtype =20;
