/*	EQEMu: Everquest Server Emulator
	Copyright (C) 2001-2016 EQEMu Development Team (http://eqemu.org)

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; version 2 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY except by those people which sell it, which
	are required to give you total support for your newly bought product;
	without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE. See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*/

#ifndef RACES_H
#define RACES_H
#include "../common/types.h"
#include <string>
#include <map>

const char* GetRaceIDName(uint16 race_id);
const char* GetGenderName(uint8 gender_id);

bool IsPlayerRace(uint16 race_id);
const std::string GetPlayerRaceAbbreviation(uint16 race_id);

uint32 GetPlayerRaceValue(uint16 race_id);
uint32 GetPlayerRaceBit(uint16 race_id);

float GetRaceGenderDefaultHeight(int race, int gender);

// player race-/gender-based model feature validators
namespace PlayerAppearance
{
	bool IsValidBeard(uint16 race_id, uint8 gender_id, uint8 beard_value, bool use_luclin = true);
	bool IsValidBeardColor(uint16 race_id, uint8 gender_id, uint8 beard_color_value, bool use_luclin = true);
	bool IsValidDetail(uint16 race_id, uint8 gender_id, uint32 detail_value, bool use_luclin = true);
	bool IsValidEyeColor(uint16 race_id, uint8 gender_id, uint8 eye_color_value, bool use_luclin = true);
	bool IsValidFace(uint16 race_id, uint8 gender_id, uint8 face_value, bool use_luclin = true);
	bool IsValidHair(uint16 race_id, uint8 gender_id, uint8 hair_value, bool use_luclin = true);
	bool IsValidHairColor(uint16 race_id, uint8 gender_id, uint8 hair_color_value, bool use_luclin = true);
	bool IsValidHead(uint16 race_id, uint8 gender_id, uint8 head_value, bool use_luclin = true);
	bool IsValidHeritage(uint16 race_id, uint8 gender_id, uint32 heritage_value, bool use_luclin = true);
	bool IsValidTattoo(uint16 race_id, uint8 gender_id, uint32 tattoo_value, bool use_luclin = true);
	bool IsValidTexture(uint16 race_id, uint8 gender_id, uint8 texture_value, bool use_luclin = true);
	bool IsValidWoad(uint16 race_id, uint8 gender_id, uint8 woad_value, bool use_luclin = true);
}

enum Races {
	Doug                     = 0,
	Human                    = 1,
	Barbarian                = 2,
	Erudite                  = 3,
	WoodElf                  = 4,
	HighElf                  = 5,
	DarkElf                  = 6,
	HalfElf                  = 7,
	Dwarf                    = 8,
	Troll                    = 9,
	Ogre                     = 10,
	Halfling                 = 11,
	Gnome                    = 12,
	Aviak                    = 13,
	Werewolf                 = 14,
	Brownie                  = 15,
	Centaur                  = 16,
	Golem                    = 17,
	Giant                    = 18,
	Trakanon                 = 19,
	VenrilSathir             = 20,
	EvilEye                  = 21,
	Beetle                   = 22,
	Kerran                   = 23,
	Fish                     = 24,
	Fairy                    = 25,
	Froglok                  = 26,
	FroglokGhoul             = 27,
	Fungusman                = 28,
	Gargoyle                 = 29,
	Gasbag                   = 30,
	GelatinousCube           = 31,
	Ghost                    = 32,
	Ghoul                    = 33,
	GiantBat                 = 34,
	GiantEel                 = 35,
	GiantRat                 = 36,
	GiantSnake               = 37,
	GiantSpider              = 38,
	Gnoll                    = 39,
	Goblin                   = 40,
	Gorilla                  = 41,
	Wolf                     = 42,
	Bear                     = 43,
	FreeportGuard            = 44,
	DemiLich                 = 45,
	Imp                      = 46,
	Griffin                  = 47,
	Kobold                   = 48,
	LavaDragon               = 49,
	Lion                     = 50,
	LizardMan                = 51,
	Mimic                    = 52,
	Minotaur                 = 53,
	Orc                      = 54,
	HumanBeggar              = 55,
	Pixie                    = 56,
	Drachnid                 = 57,
	SolusekRo                = 58,
	Bloodgill                = 59,
	Skeleton                 = 60,
	Shark                    = 61,
	Tunare                   = 62,
	Tiger                    = 63,
	Treant                   = 64,
	Vampire                  = 65,
	StatueOfRallosZek        = 66,
	HighpassCitizen          = 67,
	TentacleTerror           = 68,
	Wisp                     = 69,
	Zombie                   = 70,
	QeynosCitizen            = 71,
	Ship                     = 72,
	Launch                   = 73,
	Piranha                  = 74,
	Elemental                = 75,
	Puma                     = 76,
	NeriakCitizen            = 77,
	EruditeCitizen           = 78,
	Bixie                    = 79,
	ReanimatedHand           = 80,
	RivervaleCitizen         = 81,
	Scarecrow                = 82,
	Skunk                    = 83,
	SnakeElemental           = 84,
	Spectre                  = 85,
	Sphinx                   = 86,
	Armadillo                = 87,
	ClockworkGnome           = 88,
	Drake                    = 89,
	HalasCitizen             = 90,
	Alligator                = 91,
	GrobbCitizen             = 92,
	OggokCitizen             = 93,
	KaladimCitizen           = 94,
	CazicThule               = 95,
	Cockatrice               = 96,
	DaisyMan                 = 97,
	ElfVampire               = 98,
	Denizen                  = 99,
	Dervish                  = 100,
	Efreeti                  = 101,
	FroglokTadpole           = 102,
	PhinigelAutropos         = 103,
	Leech                    = 104,
	Swordfish                = 105,
	Felguard                 = 106,
	Mammoth                  = 107,
	EyeOfZomm                = 108,
	Wasp                     = 109,
	Mermaid                  = 110,
	Harpy                    = 111,
	Fayguard                 = 112,
	Drixie                   = 113,
	GhostShip                = 114,
	Clam                     = 115,
	SeaHorse                 = 116,
	DwarfGhost               = 117,
	EruditeGhost             = 118,
	Sabertooth               = 119,
	WolfElemental            = 120,
	Gorgon                   = 121,
	DragonSkeleton           = 122,
	Innoruuk                 = 123,
	Unicorn                  = 124,
	Pegasus                  = 125,
	Djinn                    = 126,
	InvisibleMan             = 127,
	Iksar                    = 128,
	Scorpion                 = 129,
	VahShir                  = 130,
	Sarnak                   = 131,
	Draglock                 = 132,
	Drolvarg                 = 133,
	Mosquito                 = 134,
	Rhinoceros               = 135,
	Xalgoz                   = 136,
	KunarkGoblin             = 137,
	Yeti                     = 138,
	IksarCitizen             = 139,
	ForestGiant              = 140,
	Boat                     = 141,
	MinorIllusion            = 142,
	Tree                     = 143,
	Burynai                  = 144,
	Goo                      = 145,
	SarnakSpirit             = 146,
	IksarSpirit              = 147,
	KunarkFish               = 148,
	IksarScorpion            = 149,
	Erollisi                 = 150,
	Tribunal                 = 151,
	Bertoxxulous             = 152,
	Bristlebane              = 153,
	FayDrake                 = 154,
	UndeadSarnak             = 155,
	Ratman                   = 156,
	Wyvern                   = 157,
	Wurm                     = 158,
	Devourer                 = 159,
	IksarGolem               = 160,
	UndeadIksar              = 161,
	ManEatingPlant           = 162,
	Raptor                   = 163,
	SarnakGolem              = 164,
	WaterDragon              = 165,
	AnimatedHand             = 166,
	Succulent                = 167,
	Holgresh                 = 168,
	Brontotherium            = 169,
	SnowDervish              = 170,
	DireWolf                 = 171,
	Manticore                = 172,
	Totem                    = 173,
	IceSpectre               = 174,
	EnchantedArmor           = 175,
	SnowRabbit               = 176,
	Walrus                   = 177,
	Geonid                   = 178,
	Unknown                  = 179,
	Unknown2                 = 180,
	Yakkar                   = 181,
	Faun                     = 182,
	Coldain                  = 183,
	VeliousDragon            = 184,
	Hag                      = 185,
	Hippogriff               = 186,
	Siren                    = 187,
	FrostGiant               = 188,
	StormGiant               = 189,
	Othmir                   = 190,
	Ulthork                  = 191,
	ClockworkDragon          = 192,
	Abhorrent                = 193,
	SeaTurtle                = 194,
	BlackAndWhiteDragon      = 195,
	GhostDragon              = 196,
	RonnieTest               = 197,
	PrismaticDragon          = 198,
	Shiknar                  = 199,
	Rockhopper               = 200,
	Underbulk                = 201,
	Grimling                 = 202,
	Worm                     = 203,
	EvanTest                 = 204,
	KhatiSha                 = 205,
	Owlbear                  = 206,
	RhinoBeetle              = 207,
	Vampire2                 = 208,
	EarthElemental           = 209,
	AirElemental             = 210,
	WaterElemental           = 211,
	FireElemental            = 212,
	WetfangMinnow            = 213,
	ThoughtHorror            = 214,
	Tegi                     = 215,
	HorseMount               = 216,
	Shissar                  = 217,
	FungalFiend              = 218,
	VampireVolatalis         = 219,
	Stonegrabber             = 220,
	ScarletCheetah           = 221,
	Zelniak                  = 222,
	Lightcrawler             = 223,
	Shade                    = 224,
	Sunflower                = 225,
	Shadel                   = 226,
	Shrieker                 = 227,
	Galorian                 = 228,
	Netherbian               = 229,
	Akhevan                  = 230,
	GriegVeneficus           = 231,
	SonicWolf                = 232,
	GroundShaker             = 233,
	VahShirSkeleton          = 234,
	Wretch                   = 235,
	LordInquisitorSeru       = 236,
	Recuso                   = 237,
	VahShirKing              = 238,
	VahShirGuard             = 239,
	TeleportMan              = 240,
	Werewolf2                = 241,
	Nymph                    = 242,
	Dryad                    = 243,
	Treant2                  = 244,
	Fly                      = 245,
	TarewMarr                = 246,
	SolusekRo2               = 247,
	ClockworkGolem           = 248,
	ClockworkBrain           = 249,
	Banshee                  = 250,
	GuardOfJustice           = 251,
	MiniPom                  = 252,
	DiseasedFiend            = 253,
	SolusekRoGuard           = 254,
	BertoxxulousNew          = 255,
	TribunalNew              = 256,
	TerrisThule              = 257,
	Vegerog                  = 258,
	Crocodile                = 259,
	Bat                      = 260,
	Hraquis                  = 261,
	Tranquilion              = 262,
	TinSoldier               = 263,
	NightmareWraith          = 264,
	Malarian                 = 265,
	KnightOfPestilence       = 266,
	Lepertoloth              = 267,
	Bubonian                 = 268,
	BubonianUnderling        = 269,
	Pusling                  = 270,
	WaterMephit              = 271,
	Stormrider               = 272,
	JunkBeast                = 273,
	BrokenClockwork          = 274,
	GiantClockwork           = 275,
	ClockworkBeetle          = 276,
	NightmareGoblin          = 277,
	Karana                   = 278,
	BloodRaven               = 279,
	NightmareGargoyle        = 280,
	MouthOfInsanity          = 281,
	SkeletalHorse            = 282,
	Saryrn                   = 283,
	FenninRo                 = 284,
	Tormentor                = 285,
	SoulDevourer             = 286,
	Nightmare                = 287,
	NewRallosZek             = 288,
	VallonZek                = 289,
	TallonZek                = 290,
	AirMephit                = 291,
	EarthMephit              = 292,
	FireMephit               = 293,
	NightmareMephit          = 294,
	Zebuxoruk                = 295,
	MithanielMarr            = 296,
	UndeadKnight             = 297,
	Rathe                    = 298,
	Xegony                   = 299,
	Fiend                    = 300,
	TestObject               = 301,
	Crab                     = 302,
	Phoenix                  = 303,
	Quarm                    = 304,
	Bear2                    = 305,
	EarthGolem               = 306,
	IronGolem                = 307,
	StormGolem               = 308,
	AirGolem                 = 309,
	WoodGolem                = 310,
	FireGolem                = 311,
	WaterGolem               = 312,
	WarWraith                = 313,
	Wrulon                   = 314,
	Kraken                   = 315,
	PoisonFrog               = 316,
	Nilborien                = 317,
	Valorian                 = 318,
	WarBoar                  = 319,
	Efreeti2                 = 320,
	WarBoar2                 = 321,
	Valorian2                = 322,
	AnimatedArmor            = 323,
	UndeadFootman            = 324,
	RallosOgre               = 325,
	Arachnid                 = 326,
	CrystalSpider            = 327,
	ZebuxoruksCage           = 328,
	Portal                   = 329,
	Froglok2                 = 330,
	TrollCrewMember          = 331,
	PirateDeckhand           = 332,
	BrokenSkullPirate        = 333,
	PirateGhost              = 334,
	OneArmedPirate           = 335,
	SpiritmasterNadox        = 336,
	BrokenSkullTaskmaster    = 337,
	GnomePirate              = 338,
	DarkElfPirate            = 339,
	OgrePirate               = 340,
	HumanPirate              = 341,
	EruditePirate            = 342,
	Frog                     = 343,
	TrollZombie              = 344,
	Luggald                  = 345,
	Luggald2                 = 346,
	Luggald3                 = 347,
	Drogmor                  = 348,
	FroglokSkeleton          = 349,
	UndeadFroglok            = 350,
	KnightOfHate             = 351,
	ArcanistOfHate           = 352,
	Veksar                   = 353,
	Veksar2                  = 354,
	Veksar3                  = 355,
	Chokidai                 = 356,
	UndeadChokidai           = 357,
	UndeadVeksar             = 358,
	UndeadVampire            = 359,
	Vampire3                 = 360,
	RujarkianOrc             = 361,
	BoneGolem                = 362,
	Synarcana                = 363,
	SandElf                  = 364,
	MasterVampire            = 365,
	MasterOrc                = 366,
	Skeleton2                = 367,
	Mummy                    = 368,
	NewGoblin                = 369,
	Insect                   = 370,
	FroglokGhost             = 371,
	Dervish2                 = 372,
	Shade2                   = 373,
	Golem2                   = 374,
	EvilEye2                 = 375,
	Box                      = 376,
	Barrel                   = 377,
	Chest                    = 378,
	Vase                     = 379,
	Table                    = 380,
	WeaponRack               = 381,
	Coffin                   = 382,
	Bones                    = 383,
	Jokester                 = 384,
	Nihil                    = 385,
	Trusik                   = 386,
	StoneWorker              = 387,
	Hynid                    = 388,
	Turepta                  = 389,
	Cragbeast                = 390,
	Stonemite                = 391,
	Ukun                     = 392,
	Ixt                      = 393,
	Ikaav                    = 394,
	Aneuk                    = 395,
	Kyv                      = 396,
	Noc                      = 397,
	Ratuk                    = 398,
	Taneth                   = 399,
	Huvul                    = 400,
	Mutna                    = 401,
	Mastruq                  = 402,
	Taelosian                = 403,
	DiscordShip              = 404,
	StoneWorker2             = 405,
	MataMuram                = 406,
	LightingWarrior          = 407,
	Succubus                 = 408,
	Bazu                     = 409,
	Feran                    = 410,
	Pyrilen                  = 411,
	Chimera                  = 412,
	Dragorn                  = 413,
	Murkglider               = 414,
	Rat                      = 415,
	Bat2                     = 416,
	Gelidran                 = 417,
	Discordling              = 418,
	Girplan                  = 419,
	Minotaur2                = 420,
	DragornBox               = 421,
	RunedOrb                 = 422,
	DragonBones              = 423,
	MuramiteArmorPile        = 424,
	CrystalShard             = 425,
	Portal2                  = 426,
	CoinPurse                = 427,
	RockPile                 = 428,
	MurkgliderEggSack        = 429,
	Drake2                   = 430,
	Dervish3                 = 431,
	Drake3                   = 432,
	Goblin2                  = 433,
	Kirin                    = 434,
	Dragon                   = 435,
	Basilisk                 = 436,
	Dragon2                  = 437,
	Dragon3                  = 438,
	Puma2                    = 439,
	Spider                   = 440,
	SpiderQueen              = 441,
	AnimatedStatue           = 442,
	Unknown3                 = 443,
	Unknown4                 = 444,
	DragonEgg                = 445,
	DragonStatue             = 446,
	LavaRock                 = 447,
	AnimatedStatue2          = 448,
	SpiderEggSack            = 449,
	LavaSpider               = 450,
	LavaSpiderQueen          = 451,
	Dragon4                  = 452,
	Giant2                   = 453,
	Werewolf3                = 454,
	Kobold2                  = 455,
	Sporali                  = 456,
	Gnomework                = 457,
	Orc2                     = 458,
	Corathus                 = 459,
	Coral                    = 460,
	Drachnid2                = 461,
	DrachnidCocoon           = 462,
	FungusPatch              = 463,
	Gargoyle2                = 464,
	Witheran                 = 465,
	DarkLord                 = 466,
	Shiliskin                = 467,
	Snake                    = 468,
	EvilEye3                 = 469,
	Minotaur3                = 470,
	Zombie2                  = 471,
	ClockworkBoar            = 472,
	Fairy2                   = 473,
	Witheran2                = 474,
	AirElemental2            = 475,
	EarthElemental2          = 476,
	FireElemental2           = 477,
	WaterElemental2          = 478,
	Alligator2               = 479,
	Bear3                    = 480,
	ScaledWolf               = 481,
	Wolf2                    = 482,
	SpiritWolf               = 483,
	Skeleton3                = 484,
	Spectre2                 = 485,
	Bolvirk                  = 486,
	Banshee2                 = 487,
	Banshee3                 = 488,
	Elddar                   = 489,
	ForestGiant2             = 490,
	BoneGolem2               = 491,
	HorseMount2              = 492,
	Pegasus2                 = 493,
	ShamblingMound           = 494,
	Scrykin                  = 495,
	Treant3                  = 496,
	Vampire4                 = 497,
	AyonaeRo                 = 498,
	SullonZek                = 499,
	Banner                   = 500,
	Flag                     = 501,
	Rowboat                  = 502,
	BearTrap                 = 503,
	ClockworkBomb            = 504,
	DynamiteKeg              = 505,
	PressurePlate            = 506,
	PufferSpore              = 507,
	StoneRing                = 508,
	RootTentacle             = 509,
	RunicSymbol              = 510,
	SaltpetterBomb           = 511,
	FloatingSkull            = 512,
	SpikeTrap                = 513,
	Totem2                   = 514,
	Web                      = 515,
	WickerBasket             = 516,
	Unicorn2                 = 517,
	HorseMount3              = 518,
	Unicorn3                 = 519,
	Bixie2                   = 520,
	Centaur2                 = 521,
	Drakkin                  = 522,
	Giant3                   = 523,
	Gnoll2                   = 524,
	Griffin2                 = 525,
	GiantShade               = 526,
	Harpy2                   = 527,
	Mammoth2                 = 528,
	Satyr                    = 529,
	Dragon5                  = 530,
	Dragon6                  = 531,
	Dynleth                  = 532,
	Boat2                    = 533,
	WeaponRack2              = 534,
	ArmorRack                = 535,
	HoneyPot                 = 536,
	JumJumBucket             = 537,
	Plant                    = 538,
	StoneJug                 = 539,
	Plant2                   = 540,
	Toolbox                  = 541,
	WineCask                 = 542,
	StoneJug2                = 543,
	ElvenBoat                = 544,
	GnomishBoat              = 545,
	UndeadBoat               = 546,
	Goo2                     = 547,
	Goo3                     = 548,
	Goo4                     = 549,
	MerchantShip             = 550,
	PirateShip               = 551,
	GhostShip2               = 552,
	Banner2                  = 553,
	Banner3                  = 554,
	Banner4                  = 555,
	Banner5                  = 556,
	Banner6                  = 557,
	Aviak2                   = 558,
	Beetle2                  = 559,
	Gorilla2                 = 560,
	Kedge                    = 561,
	Kerran2                  = 562,
	Shissar2                 = 563,
	Siren2                   = 564,
	Sphinx2                  = 565,
	Human2                   = 566,
	Campfire                 = 567,
	Brownie2                 = 568,
	Dragon7                  = 569,
	Exoskeleton              = 570,
	Ghoul2                   = 571,
	ClockworkGuardian        = 572,
	Unknown5                 = 573,
	Minotaur4                = 574,
	Scarecrow2               = 575,
	Shade3                   = 576,
	Rotocopter               = 577,
	TentacleTerror2          = 578,
	Wereorc                  = 579,
	Worg                     = 580,
	Wyvern2                  = 581,
	Chimera2                 = 582,
	Kirin2                   = 583,
	Puma3                    = 584,
	Boulder                  = 585,
	Banner7                  = 586,
	ElvenGhost               = 587,
	HumanGhost               = 588,
	Chest2                   = 589,
	Chest3                   = 590,
	Crystal                  = 591,
	Coffin2                  = 592,
	GuardianCpu              = 593,
	Worg2                    = 594,
	Mansion                  = 595,
	FloatingIsland           = 596,
	Cragslither              = 597,
	Wrulon2                  = 598,
	SpellParticle            = 599,
	InvisibleManOfZomm       = 600,
	RobocopterOfZomm         = 601,
	Burynai2                 = 602,
	Frog2                    = 603,
	Dracolich                = 604,
	IksarGhost               = 605,
	IksarSkeleton            = 606,
	Mephit                   = 607,
	Muddite                  = 608,
	Raptor2                  = 609,
	Sarnak2                  = 610,
	Scorpion2                = 611,
	Tsetsian                 = 612,
	Wurm2                    = 613,
	Nekhon                   = 614,
	HydraCrystal             = 615,
	CrystalSphere            = 616,
	Gnoll3                   = 617,
	Sokokar                  = 618,
	StonePylon               = 619,
	DemonVulture             = 620,
	Wagon                    = 621,
	GodOfDiscord             = 622,
	FeranMount               = 623,
	Ogre2                    = 624,
	SokokarMount             = 625,
	Giant4                   = 626,
	SokokarMount2            = 627,
	TenthAnniversaryBanner   = 628,
	TenthAnniversaryCake     = 629,
	WineCask2                = 630,
	HydraMount               = 631,
	Hydra                    = 632,
	WeddingFlowers           = 633,
	WeddingArbor             = 634,
	WeddingAltar             = 635,
	PowderKeg                = 636,
	Apexus                   = 637,
	Bellikos                 = 638,
	BrellsFirstCreation      = 639,
	Brell                    = 640,
	CrystalskinAmbuloid      = 641,
	CliknarQueen             = 642,
	CliknarSoldier           = 643,
	CliknarWorker            = 644,
	Coldain2                 = 645,
	Coldain3                 = 646,
	CrystalskinSessiloid     = 647,
	Genari                   = 648,
	Gigyn                    = 649,
	GrekenYoungAdult         = 650,
	GrekenYoung              = 651,
	CliknarMount             = 652,
	Telmira                  = 653,
	SpiderMount              = 654,
	BearMount                = 655,
	RatMount                 = 656,
	SessiloidMount           = 657,
	MorellThule              = 658,
	Marionette               = 659,
	BookDervish              = 660,
	TopiaryLion              = 661,
	RotDog                   = 662,
	Amygdalan                = 663,
	Sandman                  = 664,
	GrandfatherClock         = 665,
	GingerbreadMan           = 666,
	RoyalGuard               = 667,
	Rabbit                   = 668,
	BlindDreamer             = 669,
	CazicThule2              = 670,
	TopiaryLionMount         = 671,
	RotDogMount              = 672,
	GoralMount               = 673,
	SelyrahMount             = 674,
	ScleraMount              = 675,
	BraxiMount               = 676,
	KangonMount              = 677,
	Erudite2                 = 678,
	WurmMount                = 679,
	RaptorMount              = 680,
	InvisibleMan2            = 681,
	Whirligig                = 682,
	GnomishBalloon           = 683,
	GnomishRocketPack        = 684,
	GnomishHoveringTransport = 685,
	Selyrah                  = 686,
	Goral                    = 687,
	Braxi                    = 688,
	Kangon                   = 689,
	InvisibleMan3            = 690,
	FloatingTower            = 691,
	ExplosiveCart            = 692,
	BlimpShip                = 693,
	Tumbleweed               = 694,
	Alaran                   = 695,
	Swinetor                 = 696,
	Triumvirate              = 697,
	Hadal                    = 698,
	HoveringPlatform         = 699,
	ParasiticScavenger       = 700,
	Grendlaen                = 701,
	ShipInABottle            = 702,
	AlaranSentryStone        = 703,
	Dervish4                 = 704,
	RegenerationPool         = 705,
	TeleportationStand       = 706,
	RelicCase                = 707,
	AlaranGhost              = 708,
	Skystrider               = 709,
	WaterSpout               = 710,
	AviakPullAlong           = 711,
	GelatinousCube2          = 712,
	Cat                      = 713,
	ElkHead                  = 714,
	Holgresh2                = 715,
	Beetle3                  = 716,
	VineMaw                  = 717,
	Ratman2                  = 718,
	FallenKnight             = 719,
	FlyingCarpet             = 720,
	CarrierHand              = 721,
	Akheva                   = 722,
	ServantOfShadow          = 723,
	Luclin                   = 724,
	Xaric                    = 725,
	Dervish5                 = 726,
	Dervish6                 = 727,
	Luclin2                  = 728,
	Luclin3                  = 729,
	Orb                      = 730,
	Luclin4                  = 731,
	Pegasus3                 = 732,
	InteractiveObject        = 2250,
	Node                     = 2254,
};

enum Genders : uint8 {
	Male,
	Female,
	Neuter
};

constexpr uint16 ALL_RACES_BITMASK = 65535;

static std::map<uint16, uint16> player_race_bitmasks = {
	{Races::Human,     1},
	{Races::Barbarian, 2},
	{Races::Erudite,   4},
	{Races::WoodElf,   8},
	{Races::HighElf,   16},
	{Races::DarkElf,   32},
	{Races::HalfElf,   64},
	{Races::Dwarf,     128},
	{Races::Troll,     256},
	{Races::Ogre,      512},
	{Races::Halfling,  1024},
	{Races::Gnome,     2048},
	{Races::Iksar,     4096},
	{Races::VahShir,   8192},
	{Races::Froglok,   16384},
	{Races::Drakkin,   32768},
};

static std::map<uint16, uint8> player_race_indexes = {
	{Races::Human,     1},
	{Races::Barbarian, 2},
	{Races::Erudite,   3},
	{Races::WoodElf,   4},
	{Races::HighElf,   5},
	{Races::DarkElf,   6},
	{Races::HalfElf,   7},
	{Races::Dwarf,     8},
	{Races::Troll,     9},
	{Races::Ogre,      10},
	{Races::Halfling,  11},
	{Races::Gnome,     12},
	{Races::Iksar,     13},
	{Races::VahShir,   14},
	{Races::Froglok,   15},
	{Races::Drakkin,   16},
};

static std::map<uint32, std::string> gender_names = {
	{Genders::Male,   "Male"},
	{Genders::Female, "Female"},
	{Genders::Neuter, "Neuter"},
};

#endif

