#ifndef RULE_CATEGORY
#define RULE_CATEGORY(name)
#endif
#ifndef RULE_INT
#define RULE_INT(cat, rule, default_value)
#endif
#ifndef RULE_REAL
#define RULE_REAL(cat, rule, default_value)
#endif
#ifndef RULE_BOOL
#define RULE_BOOL(cat, rule, default_value)
#endif
#ifndef RULE_CATEGORY_END
#define RULE_CATEGORY_END()
#endif

RULE_CATEGORY(Character)
RULE_INT(Character, MaxLevel, 65)
RULE_BOOL(Character, PerCharacterQglobalMaxLevel, false)
RULE_INT(Character, MaxExpLevel, 0)
RULE_INT(Character, DeathExpLossLevel, 10)
RULE_INT(Character, DeathExpLossMaxLevel, 255)
RULE_INT(Character, DeathItemLossLevel, 10)
RULE_INT(Character, DeathExpLossMultiplier, 3)
RULE_BOOL(Character, UseDeathExpLossMult, false)
RULE_INT(Character, CorpseDecayTimeMS, 10800000)
RULE_INT(Character, CorpseResTimeMS, 10800000)
RULE_BOOL(Character, LeaveCorpses, true)
RULE_BOOL(Character, LeaveNakedCorpses, false)
RULE_INT(Character, MaxDraggedCorpses, 2)
RULE_REAL(Character, DragCorpseDistance, 400)
RULE_REAL(Character, ExpMultiplier, 0.5)
RULE_REAL(Character, AAExpMultiplier, 0.5)
RULE_REAL(Character, GroupExpMultiplier, 0.5)
RULE_REAL(Character, RaidExpMultiplier, 0.2)
RULE_BOOL(Character, UseXPConScaling, true)
RULE_INT(Character, LightBlueModifier, 40)
RULE_INT(Character, BlueModifier, 90)
RULE_INT(Character, WhiteModifier, 100)
RULE_INT(Character, YellowModifier, 125)
RULE_INT(Character, RedModifier, 150)
RULE_INT(Character, AutosaveIntervalS, 300)
RULE_INT(Character, HPRegenMultiplier, 100)
RULE_INT(Character, ManaRegenMultiplier, 100)
RULE_INT(Character, EnduranceRegenMultiplier, 100)
RULE_INT(Character, ConsumptionMultiplier, 100)
RULE_BOOL(Character, HealOnLevel, false)
RULE_BOOL(Character, FeignKillsPet, false)
RULE_INT(Character, ItemManaRegenCap, 15)
RULE_INT(Character, ItemHealthRegenCap, 35)
RULE_INT(Character, ItemDamageShieldCap, 30)
RULE_INT(Character, ItemAccuracyCap, 150)
RULE_INT(Character, ItemAvoidanceCap, 100)
RULE_INT(Character, ItemCombatEffectsCap, 100)
RULE_INT(Character, ItemShieldingCap, 35)
RULE_INT(Character, ItemSpellShieldingCap, 35)
RULE_INT(Character, ItemDoTShieldingCap, 35)
RULE_INT(Character, ItemStunResistCap, 35)
RULE_INT(Character, ItemStrikethroughCap, 35)
RULE_INT(Character, ItemATKCap, 250)
RULE_INT(Character, ItemHealAmtCap, 250)
RULE_INT(Character, ItemSpellDmgCap, 250)
RULE_INT(Character, ItemClairvoyanceCap, 250)
RULE_INT(Character, ItemDSMitigationCap, 50)
RULE_INT(Character, ItemEnduranceRegenCap, 15)
RULE_INT(Character, ItemExtraDmgCap, 150)
RULE_INT(Character, HasteCap, 100)
RULE_INT(Character, SkillUpModifier, 100)
RULE_BOOL(Character, SharedBankPlat, false)
RULE_BOOL(Character, BindAnywhere, false)
RULE_INT(Character, RestRegenPercent, 0)
RULE_INT(Character, RestRegenTimeToActivate, 30)
RULE_BOOL(Character, RestRegenEndurance, false)
RULE_INT(Character, KillsPerGroupLeadershipAA, 250)
RULE_INT(Character, KillsPerRaidLeadershipAA, 250)
RULE_INT(Character, MaxFearDurationForPlayerCharacter, 4)
RULE_INT(Character, MaxCharmDurationForPlayerCharacter, 15)
RULE_INT(Character, BaseHPRegenBonusRaces, 4352)
RULE_BOOL(Character, SoDClientUseSoDHPManaEnd, false)
RULE_BOOL(Character, UseRaceClassExpBonuses, true)
RULE_BOOL(Character, RespawnFromHover, false)
RULE_INT(Character, RespawnFromHoverTimer, 300)
RULE_BOOL(Character, UseNewStatsWindow, true)
RULE_BOOL(Character, ItemCastsUseFocus, false)
RULE_INT(Character, MinStatusForNoDropExemptions, 80)
RULE_INT(Character, SkillCapMaxLevel, 75)
RULE_INT(Character, StatCap, 0)
RULE_BOOL(Character, CheckCursorEmptyWhenLooting, true)
RULE_BOOL(Character, MaintainIntoxicationAcrossZones, true)
RULE_BOOL(Character, EnableDiscoveredItems, true)
RULE_BOOL(Character, EnableXTargetting, true)
RULE_BOOL(Character, KeepLevelOverMax, false)
RULE_INT(Character, FoodLossPerUpdate, 35)
RULE_INT(Character, BaseInstrumentSoftCap, 36)
RULE_INT(Character, BaseRunSpeedCap, 158)
RULE_CATEGORY_END()

RULE_CATEGORY(Mercs)
RULE_INT(Mercs, SuspendIntervalMS, 10000)
RULE_INT(Mercs, UpkeepIntervalMS, 180000)
RULE_INT(Mercs, SuspendIntervalS, 10)
RULE_INT(Mercs, UpkeepIntervalS, 180)
RULE_BOOL(Mercs, AllowMercs, false)
RULE_BOOL(Mercs, ChargeMercPurchaseCost, false)
RULE_BOOL(Mercs, ChargeMercUpkeepCost, false)
RULE_INT(Mercs, AggroRadius, 100)
RULE_INT(Mercs, AggroRadiusPuller, 25)
RULE_INT(Mercs, ResurrectRadius, 50)
RULE_INT(Mercs, ScaleRate, 100)
RULE_CATEGORY_END()

RULE_CATEGORY(Guild)
RULE_INT(Guild, MaxMembers, 2048)
RULE_BOOL(Guild, PlayerCreationAllowed, false)
RULE_INT(Guild, PlayerCreationLimit, 1)
RULE_INT(Guild, PlayerCreationRequiredStatus, 0)
RULE_INT(Guild, PlayerCreationRequiredLevel, 0)
RULE_INT(Guild, PlayerCreationRequiredTime, 0)
RULE_CATEGORY_END()

RULE_CATEGORY(Skills)
RULE_INT(Skills, MaxTrainTradeskills, 21)
RULE_BOOL(Skills, UseLimitTradeskillSearchSkillDiff, true)
RULE_INT(Skills, MaxTradeskillSearchSkillDiff, 50)
RULE_INT(Skills, MaxTrainSpecializations, 50)
RULE_CATEGORY_END()

RULE_CATEGORY(Pets)
RULE_REAL(Pets, AttackCommandRange, 150)
RULE_BOOL(Pets, UnTargetableSwarmPet, false)
RULE_BOOL(Pets, SwarmPetNotTargetableWithHotKey, false)
RULE_CATEGORY_END()

RULE_CATEGORY(GM)
RULE_INT(GM, MinStatusToSummonItem, 250)
RULE_INT(GM, MinStatusToZoneAnywhere, 250)
RULE_CATEGORY_END()

RULE_CATEGORY(World)
RULE_INT(World, ZoneAutobootTimeoutMS, 60000)
RULE_INT(World, ClientKeepaliveTimeoutMS, 65000)
RULE_BOOL(World, UseBannedIPsTable, false)
RULE_BOOL(World, EnableTutorialButton, true)
RULE_BOOL(World, EnableReturnHomeButton, true)
RULE_INT(World, MaxLevelForTutorial, 10)
RULE_INT(World, TutorialZoneID, 189)
RULE_INT(World, GuildBankZoneID, 345)
RULE_INT(World, MinOfflineTimeToReturnHome, 21600)
RULE_INT(World, MaxClientsPerIP, -1)
RULE_INT(World, ExemptMaxClientsStatus, -1)
RULE_INT(World, AddMaxClientsPerIP, -1)
RULE_INT(World, AddMaxClientsStatus, -1)
RULE_BOOL(World, MaxClientsSetByStatus, false)
RULE_BOOL(World, ClearTempMerchantlist, true)
RULE_BOOL(World, DeleteStaleCorpeBackups, true)
RULE_INT(World, AccountSessionLimit, -1)
RULE_INT(World, ExemptAccountLimitStatus, -1)
RULE_BOOL(World, GMAccountIPList, false)
RULE_INT(World, MinGMAntiHackStatus, 1)
RULE_INT(World, SoFStartZoneID, -1)
RULE_INT(World, ExpansionSettings, 16383)
RULE_INT(World, PVPSettings, 0)
RULE_BOOL(World, IsGMPetitionWindowEnabled, false)
RULE_INT(World, FVNoDropFlag, 0)
RULE_BOOL(World, IPLimitDisconnectAll, false)
RULE_CATEGORY_END()

RULE_CATEGORY(Zone)
RULE_INT(Zone, NPCPositonUpdateTicCount, 32)
RULE_INT(Zone, ClientLinkdeadMS, 180000)
RULE_INT(Zone, GraveyardTimeMS, 1200000)
RULE_BOOL(Zone, EnableShadowrest, 1)
RULE_BOOL(Zone, UsePlayerCorpseBackups, true)
RULE_INT(Zone, MQWarpExemptStatus, -1)
RULE_INT(Zone, MQZoneExemptStatus, -1)
RULE_INT(Zone, MQGateExemptStatus, -1)
RULE_INT(Zone, MQGhostExemptStatus, -1)
RULE_BOOL(Zone, EnableMQWarpDetector, true)
RULE_BOOL(Zone, EnableMQZoneDetector, true)
RULE_BOOL(Zone, EnableMQGateDetector, true)
RULE_BOOL(Zone, EnableMQGhostDetector, true)
RULE_REAL(Zone, MQWarpDetectionDistanceFactor, 9.0)
RULE_BOOL(Zone, MarkMQWarpLT, false)
RULE_INT(Zone, AutoShutdownDelay, 5000)
RULE_INT(Zone, PEQZoneReuseTime, 900)
RULE_INT(Zone, PEQZoneDebuff1, 4454)
RULE_INT(Zone, PEQZoneDebuff2, 2209)
RULE_BOOL(Zone, UsePEQZoneDebuffs, true)
RULE_REAL(Zone, HotZoneBonus, 0.75)
RULE_INT(Zone, ReservedInstances, 30)
RULE_INT(Zone, EbonCrystalItemID, 40902)
RULE_INT(Zone, RadiantCrystalItemID, 40903)
RULE_BOOL(Zone, LevelBasedEXPMods, false)
RULE_INT(Zone, WeatherTimer, 600)
RULE_CATEGORY_END()

RULE_CATEGORY(Map)
RULE_BOOL(Map, FixPathingZWhenLoading, true)
RULE_BOOL(Map, FixPathingZAtWaypoints, false)
RULE_BOOL(Map, FixPathingZWhenMoving, false)
RULE_BOOL(Map, FixPathingZOnSendTo, false)
RULE_REAL(Map, FixPathingZMaxDeltaMoving, 20)
RULE_REAL(Map, FixPathingZMaxDeltaWaypoint, 20)
RULE_REAL(Map, FixPathingZMaxDeltaSendTo, 20)
RULE_REAL(Map, FixPathingZMaxDeltaLoading, 45)
RULE_BOOL(Map, UseClosestZ, false)
RULE_INT(Map, FindBestZHeightAdjust, 1)
RULE_CATEGORY_END()

RULE_CATEGORY(Pathing)
RULE_BOOL(Pathing, Aggro, true)
RULE_BOOL(Pathing, AggroReturnToGrid, true)
RULE_BOOL(Pathing, Guard, true)
RULE_BOOL(Pathing, Find, true)
RULE_BOOL(Pathing, Fear, true)
RULE_REAL(Pathing, ZDiffThreshold, 10)
RULE_INT(Pathing, LOSCheckFrequency, 1000)
RULE_INT(Pathing, RouteUpdateFrequencyShort, 1000)
RULE_INT(Pathing, RouteUpdateFrequencyLong, 5000)
RULE_INT(Pathing, RouteUpdateFrequencyNodeCount, 5)
RULE_REAL(Pathing, MinDistanceForLOSCheckShort, 40000)
RULE_REAL(Pathing, MinDistanceForLOSCheckLong, 1000000)
RULE_INT(Pathing, MinNodesLeftForLOSCheck, 4)
RULE_INT(Pathing, MinNodesTraversedForLOSCheck, 3)
RULE_INT(Pathing, CullNodesFromStart, 1)
RULE_INT(Pathing, CullNodesFromEnd, 1)
RULE_REAL(Pathing, CandidateNodeRangeXY, 400)
RULE_REAL(Pathing, CandidateNodeRangeZ, 10)
RULE_CATEGORY_END()

RULE_CATEGORY(Watermap)
RULE_BOOL(Watermap, CheckWaypointsInWaterWhenLoading, false)
RULE_BOOL(Watermap, CheckForWaterAtWaypoints, false)
RULE_BOOL(Watermap, CheckForWaterWhenMoving, false)
RULE_BOOL(Watermap, CheckForWaterOnSendTo, false)
RULE_BOOL(Watermap, CheckForWaterWhenFishing, false)
RULE_REAL(Watermap, FishingRodLength, 30)
RULE_REAL(Watermap, FishingLineLength, 40)
RULE_CATEGORY_END()

RULE_CATEGORY(Spells)
RULE_INT(Spells, AutoResistDiff, 15)
RULE_REAL(Spells, ResistChance, 2.0)
RULE_REAL(Spells, ResistMod, 0.40)
RULE_REAL(Spells, PartialHitChance, 0.7)
RULE_REAL(Spells, PartialHitChanceFear, 0.25)
RULE_INT(Spells, BaseCritChance, 0)
RULE_INT(Spells, BaseCritRatio, 100)
RULE_INT(Spells, WizCritLevel, 12)
RULE_INT(Spells, WizCritChance, 7)
RULE_INT(Spells, WizCritRatio, 0)
RULE_INT(Spells, ResistPerLevelDiff, 85)
RULE_INT(Spells, TranslocateTimeLimit, 0)
RULE_INT(Spells, SacrificeMinLevel, 46)
RULE_INT(Spells, SacrificeMaxLevel, 69)
RULE_INT(Spells, SacrificeItemID, 9963)
RULE_BOOL(Spells, EnableSpellGlobals, false)
RULE_INT(Spells, MaxBuffSlotsNPC, 25)
RULE_INT(Spells, MaxSongSlotsNPC, 10)
RULE_INT(Spells, MaxDiscSlotsNPC, 1)
RULE_INT(Spells, MaxTotalSlotsNPC, 36)
RULE_INT(Spells, MaxTotalSlotsPET, 25)
RULE_BOOL(Spells, EnableBlockedBuffs, true)
RULE_INT(Spells, ReflectType, 1)
RULE_INT(Spells, VirusSpreadDistance, 30)
RULE_BOOL(Spells, LiveLikeFocusEffects, true)
RULE_INT(Spells, BaseImmunityLevel, 55)
RULE_BOOL(Spells, NPCIgnoreBaseImmunity, true)
RULE_REAL(Spells, AvgSpellProcsPerMinute, 6.0)
RULE_INT(Spells, ResistFalloff, 67)
RULE_INT(Spells, CharismaEffectiveness, 10)
RULE_INT(Spells, CharismaEffectivenessCap, 255)
RULE_BOOL(Spells, CharismaCharmDuration, false)
RULE_INT(Spells, CharmBreakCheckChance, 25)
RULE_INT(Spells, MaxCastTimeReduction, 50)
RULE_INT(Spells, RootBreakFromSpells, 55)
RULE_INT(Spells, DeathSaveCharismaMod, 3)
RULE_INT(Spells, DivineInterventionHeal, 8000)
RULE_BOOL(Spells, AdditiveBonusValues, false)
RULE_BOOL(Spells, UseCHAScribeHack, false)
RULE_BOOL(Spells, BuffLevelRestrictions, true)
RULE_INT(Spells, RootBreakCheckChance, 70)
RULE_INT(Spells, FearBreakCheckChance, 70)
RULE_INT(Spells, SuccorFailChance, 2)
RULE_INT(Spells, FRProjectileItem_SOF, 80684)
RULE_INT(Spells, FRProjectileItem_NPC, 80684)
RULE_BOOL(Spells, UseLiveSpellProjectileGFX, false)
RULE_BOOL(Spells, FocusCombatProcs, false)
RULE_CATEGORY_END()

RULE_CATEGORY(Combat)
RULE_INT(Combat, AvoidanceCap, 1000)
RULE_INT(Combat, MeleeBaseCritChance, 0)
RULE_INT(Combat, WarBerBaseCritChance, 3)
RULE_INT(Combat, BerserkBaseCritChance, 6)
RULE_INT(Combat, NPCBashKickLevel, 6)
RULE_INT(Combat, NPCBashKickStunChance, 15)
RULE_INT(Combat, RogueCritThrowingChance, 25)
RULE_INT(Combat, RogueDeadlyStrikeChance, 80)
RULE_INT(Combat, RogueDeadlyStrikeMod, 2)
RULE_INT(Combat, ClientBaseCritChance, 0)
RULE_BOOL(Combat, UseIntervalAC, true)
RULE_INT(Combat, PetAttackMagicLevel, 30)
RULE_BOOL(Combat, EnableFearPathing, true)
RULE_REAL(Combat, FleeMultiplier, 2.0)
RULE_INT(Combat, FleeHPRatio, 25)
RULE_BOOL(Combat, FleeIfNotAlone, false)
RULE_BOOL(Combat, AdjustProcPerMinute, true)
RULE_REAL(Combat, AvgProcsPerMinute, 2.0)
RULE_REAL(Combat, ProcPerMinDexContrib, 0.075)
RULE_REAL(Combat, BaseProcChance, 0.035)
RULE_REAL(Combat, ProcDexDivideBy, 11000)
RULE_REAL(Combat, BaseHitChance, 69.0)
RULE_REAL(Combat, NPCBonusHitChance, 26.0)
RULE_REAL(Combat, HitFalloffMinor, 5.0)
RULE_REAL(Combat, HitFalloffModerate, 7.0)
RULE_REAL(Combat, HitFalloffMajor, 50.0)
RULE_REAL(Combat, HitBonusPerLevel, 1.2)
RULE_REAL(Combat, WeaponSkillFalloff, 0.33)
RULE_REAL(Combat, ArcheryHitPenalty, 0.25)
RULE_REAL(Combat, AgiHitFactor, 0.01)
RULE_INT(Combat, MinRangedAttackDist, 25)
RULE_BOOL(Combat, ArcheryBonusRequiresStationary, true)
RULE_REAL(Combat, ArcheryBaseDamageBonus, 1)
RULE_REAL(Combat, ArcheryNPCMultiplier, 1.0)
RULE_BOOL(Combat, AssistNoTargetSelf, true)
RULE_INT(Combat, MaxRampageTargets, 3)
RULE_INT(Combat, DefaultRampageTargets, 1)
RULE_BOOL(Combat, RampageHitsTarget, false)
RULE_INT(Combat, MaxFlurryHits, 2)
RULE_INT(Combat, MonkDamageTableBonus, 5)
RULE_INT(Combat, FlyingKickBonus, 25)
RULE_INT(Combat, DragonPunchBonus, 20)
RULE_INT(Combat, EagleStrikeBonus, 15)
RULE_INT(Combat, TigerClawBonus, 10)
RULE_INT(Combat, RoundKickBonus, 5)
RULE_INT(Combat, FrenzyBonus, 0)
RULE_INT(Combat, BackstabBonus, 0)
RULE_BOOL(Combat, ProcTargetOnly, true)
RULE_REAL(Combat, NPCACFactor, 2.25)
RULE_INT(Combat, ClothACSoftcap, 75)
RULE_INT(Combat, LeatherACSoftcap, 100)
RULE_INT(Combat, MonkACSoftcap, 120)
RULE_INT(Combat, ChainACSoftcap, 200)
RULE_INT(Combat, PlateACSoftcap, 300)
RULE_REAL(Combat, AAMitigationACFactor, 3.0)
RULE_REAL(Combat, WarriorACSoftcapReturn, 0.45)
RULE_REAL(Combat, KnightACSoftcapReturn, 0.33)
RULE_REAL(Combat, LowPlateChainACSoftcapReturn, 0.23)
RULE_REAL(Combat, LowChainLeatherACSoftcapReturn, 0.17)
RULE_REAL(Combat, CasterACSoftcapReturn, 0.06)
RULE_REAL(Combat, MiscACSoftcapReturn, 0.3)
RULE_BOOL(Combat, OldACSoftcapRules, false)
RULE_BOOL(Combat, UseOldDamageIntervalRules, false)
RULE_REAL(Combat, WarACSoftcapReturn, 0.3448)
RULE_REAL(Combat, ClrRngMnkBrdACSoftcapReturn, 0.3030)
RULE_REAL(Combat, PalShdACSoftcapReturn, 0.3226)
RULE_REAL(Combat, DruNecWizEncMagACSoftcapReturn, 0.2000)
RULE_REAL(Combat, RogShmBstBerACSoftcapReturn, 0.2500)
RULE_REAL(Combat, SoftcapFactor, 1.88)
RULE_REAL(Combat, ACthac0Factor, 0.55)
RULE_REAL(Combat, ACthac20Factor, 0.55)
RULE_INT(Combat, MinHastedDelay, 400)
RULE_REAL(Combat, AvgDefProcsPerMinute, 2.0)
RULE_REAL(Combat, DefProcPerMinAgiContrib, 0.075)
RULE_INT(Combat, SpecialAttackACBonus, 15)
RULE_INT(Combat, NPCFlurryChance, 20)
RULE_BOOL(Combat,TauntOverLevel, 1)
RULE_REAL(Combat,TauntSkillFalloff, 0.33)
RULE_BOOL(Combat,EXPFromDmgShield, false)
RULE_INT(Combat, MonkACBonusWeight, 15)
RULE_INT(Combat, ClientStunLevel, 55)
RULE_INT(Combat, QuiverWRHasteDiv, 3)
RULE_BOOL(Combat, UseArcheryBonusRoll, false)
RULE_INT(Combat, ArcheryBonusChance, 50)
RULE_INT(Combat, BerserkerFrenzyStart, 35)
RULE_INT(Combat, BerserkerFrenzyEnd, 45)
RULE_BOOL(Combat, OneProcPerWeapon, true)
RULE_CATEGORY_END()

RULE_CATEGORY(NPC)
RULE_INT(NPC, MinorNPCCorpseDecayTimeMS, 450000)
RULE_INT(NPC, MajorNPCCorpseDecayTimeMS, 1500000)
RULE_INT(NPC, CorpseUnlockTimer, 150000)
RULE_INT(NPC, EmptyNPCCorpseDecayTimeMS, 0)
RULE_BOOL(NPC, UseItemBonusesForNonPets, true)
RULE_INT(NPC, SayPauseTimeInSec, 5)
RULE_INT(NPC, OOCRegen, 0)
RULE_BOOL(NPC, BuffFriends, false)
RULE_BOOL(NPC, EnableNPCQuestJournal, false)
RULE_INT(NPC, LastFightingDelayMovingMin, 10000)
RULE_INT(NPC, LastFightingDelayMovingMax, 20000)
RULE_BOOL(NPC, SmartLastFightingDelayMoving, true)
RULE_BOOL(NPC, ReturnNonQuestNoDropItems, false)
RULE_INT(NPC, StartEnrageValue, 9)
RULE_BOOL(NPC, LiveLikeEnrage, false)
RULE_CATEGORY_END()

RULE_CATEGORY(Aggro)
RULE_BOOL(Aggro, SmartAggroList, true)
RULE_INT(Aggro, SittingAggroMod, 35)
RULE_INT(Aggro, MeleeRangeAggroMod, 10)
RULE_INT(Aggro, CurrentTargetAggroMod, 0)
RULE_INT(Aggro, CriticallyWoundedAggroMod, 100)
RULE_INT(Aggro, SpellAggroMod, 100)
RULE_INT(Aggro, SongAggroMod, 33)
RULE_INT(Aggro, PetSpellAggroMod, 10)
RULE_REAL(Aggro, TunnelVisionAggroMod, 0.75)
RULE_INT(Aggro, MaxStunProcAggro, 400)
RULE_INT(Aggro, IntAggroThreshold, 75)
RULE_CATEGORY_END()

RULE_CATEGORY(TaskSystem)
RULE_BOOL(TaskSystem, EnableTaskSystem, true)
RULE_INT(TaskSystem, PeriodicCheckTimer, 5)
RULE_BOOL(TaskSystem, RecordCompletedTasks, true)
RULE_BOOL(TaskSystem, RecordCompletedOptionalActivities, false)
RULE_BOOL(TaskSystem, KeepOneRecordPerCompletedTask, true)
RULE_BOOL(TaskSystem, EnableTaskProximity, true)
RULE_CATEGORY_END()

RULE_CATEGORY(Chat)
RULE_BOOL(Chat, ServerWideOOC, true)
RULE_BOOL(Chat, ServerWideAuction, true)
RULE_BOOL(Chat, EnableVoiceMacros, true)
RULE_BOOL(Chat, EnableMailKeyIPVerification, true)
RULE_BOOL(Chat, EnableAntiSpam, true)
RULE_BOOL(Chat, SuppressCommandErrors, false)
RULE_INT(Chat, MinStatusToBypassAntiSpam, 100)
RULE_INT(Chat, MinimumMessagesPerInterval, 4)
RULE_INT(Chat, MaximumMessagesPerInterval, 12)
RULE_INT(Chat, MaxMessagesBeforeKick, 20)
RULE_INT(Chat, IntervalDurationMS, 60000)
RULE_INT(Chat, KarmaUpdateIntervalMS, 1200000)
RULE_INT(Chat, KarmaGlobalChatLimit, 72)
RULE_INT(Chat, GlobalChatLevelLimit, 8)
RULE_CATEGORY_END()

RULE_CATEGORY(Merchant)
RULE_BOOL(Merchant, UsePriceMod, true)
RULE_REAL(Merchant, SellCostMod, 1.05)
RULE_REAL(Merchant, BuyCostMod, 0.95)
RULE_INT(Merchant, PriceBonusPct, 4)
RULE_INT(Merchant, PricePenaltyPct, 4)
RULE_REAL(Merchant, ChaBonusMod, 3.45)
RULE_REAL(Merchant, ChaPenaltyMod, 1.52)
RULE_BOOL(Merchant, EnableAltCurrencySell, true)
RULE_CATEGORY_END()

RULE_CATEGORY(Bazaar)
RULE_BOOL(Bazaar, AuditTrail, false)
RULE_INT(Bazaar, MaxSearchResults, 50)
RULE_BOOL(Bazaar, EnableWarpToTrader, true)
RULE_INT(Bazaar, MaxBarterSearchResults, 200)
RULE_CATEGORY_END()

RULE_CATEGORY(Mail)
RULE_BOOL(Mail, EnableMailSystem, true)
RULE_INT(Mail, ExpireTrash, 0)
RULE_INT(Mail, ExpireRead, 31536000)
RULE_INT(Mail, ExpireUnread, 31536000)
RULE_CATEGORY_END()

RULE_CATEGORY(Channels)
RULE_INT(Channels, RequiredStatusAdmin, 251)
RULE_INT(Channels, RequiredStatusListAll, 251)
RULE_INT(Channels, DeleteTimer, 1440)
RULE_CATEGORY_END()

RULE_CATEGORY(EventLog)
RULE_BOOL(EventLog, RecordSellToMerchant, false)
RULE_BOOL(EventLog, RecordBuyFromMerchant, false)
RULE_CATEGORY_END()

RULE_CATEGORY(Adventure)
RULE_INT(Adventure, MinNumberForGroup, 2)
RULE_INT(Adventure, MaxNumberForGroup, 6)
RULE_INT(Adventure, MinNumberForRaid, 18)
RULE_INT(Adventure, MaxNumberForRaid, 36)
RULE_INT(Adventure, MaxLevelRange, 9)
RULE_INT(Adventure, NumberKillsForBossSpawn, 45)
RULE_REAL(Adventure, DistanceForRescueAccept, 10000.0)
RULE_REAL(Adventure, DistanceForRescueComplete, 2500.0)
RULE_INT(Adventure, ItemIDToEnablePorts, 41000)
RULE_INT(Adventure, LDoNTrapDistanceUse, 625)
RULE_REAL(Adventure, LDoNBaseTrapDifficulty, 15.0)
RULE_REAL(Adventure, LDoNCriticalFailTrapThreshold, 10.0)
RULE_INT(Adventure, LDoNAdventureExpireTime, 1800)
RULE_CATEGORY_END()

RULE_CATEGORY(AA)
RULE_INT(AA, ExpPerPoint, 23976503)
RULE_BOOL(AA, Stacking, true)
RULE_CATEGORY_END()

RULE_CATEGORY(Console)
RULE_INT(Console, SessionTimeOut, 600000)
RULE_CATEGORY_END()

RULE_CATEGORY(QueryServ)
RULE_BOOL(QueryServ, PlayerChatLogging, false)
RULE_BOOL(QueryServ, PlayerLogTrades, false)
RULE_BOOL(QueryServ, PlayerLogHandins, false)
RULE_BOOL(QueryServ, PlayerLogNPCKills, false)
RULE_BOOL(QueryServ, PlayerLogDeletes, false)
RULE_BOOL(QueryServ, PlayerLogMoves, false)
RULE_BOOL(QueryServ, MerchantLogTransactions, false)
RULE_BOOL(QueryServ, PlayerLogPCCoordinates, false)
RULE_CATEGORY_END()

RULE_CATEGORY(Inventory)
RULE_BOOL(Inventory, EnforceAugmentRestriction, true)
RULE_BOOL(Inventory, EnforceAugmentUsability, true)
RULE_BOOL(Inventory, EnforceAugmentWear, true)
RULE_CATEGORY_END()

#undef RULE_CATEGORY
#undef RULE_INT
#undef RULE_REAL
#undef RULE_BOOL
#undef RULE_CATEGORY_END