ALTER TABLE `zone` ADD `FastRegenHP` INT NOT NULL DEFAULT '180';
ALTER TABLE `zone` ADD `FastRegenMana` INT NOT NULL DEFAULT '180';
ALTER TABLE `zone` ADD `FastRegenEndurance` INT NOT NULL DEFAULT '180';
