ALTER TABLE `zone`
    ADD COLUMN `bypass_expansion_check` tinyint(3) NOT NULL DEFAULT 0 AFTER `expansion`;

UPDATE `zone` SET `bypass_expansion_check` = 1 WHERE `short_name`
IN (
    'befallenb',
    'commonlands',
    'freeportacademy',
    'freeportarena',
    'freeportcityhall',
    'freeporteast',
    'freeporthall',
    'freeportmilitia',
    'freeportsewers',
    'freeportwest',
    'guildhall',
    'guildlobby',
    'highpasshold',
    'highpasskeep',
    'innothuleb',
    'kithforest',
    'mistythicket',
    'moors',
    'nektulosa',
    'northro',
    'oceanoftears',
    'southro',
    'steamfontmts',
    'toxxulia'
);

UPDATE `zone` SET `expansion` = 0 WHERE `id` = 244; -- nedaria
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 132; -- freportn
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 131; -- freporte
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 257; -- nro
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 60; -- cshome
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 259; -- oasis
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 439; -- nektulosnektulos
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 334; -- shadowrest
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 263; -- oggok
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 56; -- crushbone
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 133; -- freportw
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 255; -- northkarana
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 149; -- gukbottom
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 248; -- neriaka
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 249; -- neriakb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 250; -- neriakc
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 142; -- grobb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 51; -- commons
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 138; -- gfaydark
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 274; -- oot
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 276; -- paineel
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 99; -- eastkarana
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 116; -- felwitheb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 115; -- felwithea
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 114; -- feerrott
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 113; -- fearplane
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 112; -- everfrost
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 109; -- erudnint
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 108; -- erudnext
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 279; -- permafrost
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 300; -- qcat
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 301; -- qey2hh1
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 329; -- runnyeye
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 316; -- rivervale
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 278; -- paw
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 312; -- rathemtn
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 306; -- qrg
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 304; -- qeytoqrg
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 303; -- qeynos2
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 302; -- qeynos
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 104; -- ecommons
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 241; -- najena
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 353; -- soldunga
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 193; -- kedge
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 194; -- kerraridge
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 196; -- kithicor
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 172; -- hole
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 19; -- befallen
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 21; -- beholder
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 419; -- unrest
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 23; -- blackburrow
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 415; -- tutorialb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 414; -- tutoriala
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 3; -- airplane
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 4; -- akanon
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 184; -- jaggedpine
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 188; -- kaladima
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 410; -- tox
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 182; -- innothule
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 9; -- arena
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 189; -- kaladimb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 201; -- lakerathe
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 202; -- lavastorm
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 162; -- hateplane
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 160; -- halas
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 156; -- guktop
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 34; -- cauldron
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 224; -- mistmoore
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 36; -- cazicthule
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 361; -- sro
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 225; -- misty
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 31; -- butcher
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 163; -- hateplaneb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 204; -- lfaydark
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 354; -- soldungb
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 166; -- highpass
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 359; -- southkarana
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 365; -- steamfont
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 165; -- highkeep
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 107; -- emeraldjungle
UPDATE `zone` SET `expansion` = 0 WHERE `id` = 110; -- erudsxing
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 370; -- stonebrunt
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 187; -- kaesora
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 190; -- karnor
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 134; -- frontiermtns
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 199; -- kurn
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 200; -- lakeofillomen
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 275; -- overthere
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 258; -- nurga
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 120; -- firiona
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 44; -- chardok
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 33; -- cabwest
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 374; -- swampofnohope
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 422; -- veeshan
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 423; -- veksar
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 30; -- burningwood
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 345; -- skyfire
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 431; -- warslikswood
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 119; -- fieldofbone
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 331; -- sebilis
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 32; -- cabeast
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 61; -- dalnir
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 430; -- warrens
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 97; -- droga
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 412; -- trakanon
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 46; -- citymist
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 43; -- charasis
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 95; -- dreadlands
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 357; -- soltemple
UPDATE `zone` SET `expansion` = 1 WHERE `id` = 406; -- timorous
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 436; -- westwastes
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 58; -- crystal
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 405; -- thurgadinb
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 243; -- necropolis
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 344; -- sirens
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 348; -- sleeper
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 48; -- cobaltscar
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 136; -- frozenshadow
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 404; -- thurgadina
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 428; -- wakening
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 139; -- greatdivide
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 223; -- mischiefplane
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 143; -- growthplane
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 388; -- templeveeshan
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 174; -- iceclad
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 347; -- skyshrine
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 102; -- eastwastes
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 186; -- kael
UPDATE `zone` SET `expansion` = 2 WHERE `id` = 424; -- velketor
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 5; -- akheva
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 2; -- acrylia
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 393; -- thedeep
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 394; -- thegrey
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 191; -- katta
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 239; -- mseru
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 416; -- twilight
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 208; -- maiden
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 389; -- tenebrous
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 173; -- hollowshade
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 18; -- bazaar
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 203; -- letalis
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 426; -- vexthal
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 363; -- ssratemple
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 362; -- sseru
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 252; -- netherbian
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 103; -- echo
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 330; -- scarlet
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 277; -- paludal
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 332; -- shadeweaver
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 333; -- shadowhaven
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 62; -- dawnshroud
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 336; -- sharvahl
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 137; -- fungusgrove
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 140; -- griegsend
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 141; -- grimling
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 418; -- umbral
UPDATE `zone` SET `expansion` = 3 WHERE `id` = 253; -- nexus
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 288; -- ponightmare
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 289; -- postorms
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 282; -- poeartha
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 283; -- poearthb
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 284; -- pofire
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 287; -- poknowledge
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 285; -- poinnovation
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 286; -- pojustice
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 291; -- potimea
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 290; -- potactics
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 356; -- solrotower
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 297; -- powater
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 296; -- powar
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 280; -- poair
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 281; -- podisease
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 295; -- povalor
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 294; -- potranquility
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 293; -- potorment
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 292; -- potimeb
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 254; -- nightmareb
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 27; -- bothunder
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 170; -- hohonora
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 171; -- hohonorb
UPDATE `zone` SET `expansion` = 4 WHERE `id` = 49; -- codecay
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 408; -- torgiran
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 45; -- chardokb
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 240; -- nadox
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 164; -- hatesfury
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 157; -- gunthak
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 355; -- soldungc
UPDATE `zone` SET `expansion` = 5 WHERE `id` = 98; -- dulak
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 234; -- mmch
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 153; -- gukf
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 230; -- mmcd
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 231; -- mmce
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 328; -- rujj
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 217; -- mire
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 236; -- mmcj
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 232; -- mmcf
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 233; -- mmcg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 235; -- mmci
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 229; -- mmcc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 228; -- mmcb
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 327; -- ruji
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 5967; -- mirc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 5970; -- taka
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 5974; -- rujj
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 320; -- rujb
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 319; -- ruja
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 321; -- rujc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 322; -- rujd
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 323; -- ruje
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 147; -- guka
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 148; -- gukb
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 324; -- rujf
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 150; -- gukc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 325; -- rujg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 151; -- gukd
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 326; -- rujh
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 227; -- mmca
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 155; -- gukh
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 154; -- gukg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 377; -- takb
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 378; -- takc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 379; -- takd
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 380; -- take
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 381; -- takf
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 382; -- takg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 383; -- takh
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 384; -- taki
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 387; -- takj
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 152; -- guke
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 5966; -- gukc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 219; -- mirg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 221; -- miri
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 220; -- mirh
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 218; -- mirf
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 216; -- mird
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 215; -- mirc
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 214; -- mirb
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 213; -- mira
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 222; -- mirj
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 6019; -- gukg
UPDATE `zone` SET `expansion` = 6 WHERE `id` = 6018; -- take
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 407; -- tipt
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 15; -- barindu
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 349; -- sncrematory
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 375; -- tacvi
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 351; -- snplant
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 352; -- snpool
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 117; -- ferubi
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 118; -- fhalls
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 305; -- qinimi
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 1; -- abysmal
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 350; -- snlair
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 308; -- qvicb
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 317; -- riwwi
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 417; -- txevu
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 420; -- uqua
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 437; -- yxtta
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 427; -- vxed
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 307; -- qvic
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 176; -- ikkinz
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 197; -- kodtaz
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 181; -- inktuta
UPDATE `zone` SET `expansion` = 7 WHERE `id` = 242; -- natimbi
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 41; -- chamberse
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 81; -- dranikhollowsa
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 83; -- dranikhollowsc
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 91; -- draniksewersa
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 92; -- draniksewersb
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 93; -- draniksewersc
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 299; -- provinggrounds
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 79; -- dranikcatacombsb
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 40; -- chambersd
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 429; -- wallofslaughter
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 78; -- dranikcatacombsa
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 77; -- dranik
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 39; -- chambersc
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 161; -- harbingers
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 35; -- causeway
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 37; -- chambersa
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 94; -- draniksscar
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 25; -- bloodfields
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 42; -- chambersf
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 6; -- anguish
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 80; -- dranikcatacombsc
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 38; -- chambersb
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 315; -- riftseekers
UPDATE `zone` SET `expansion` = 8 WHERE `id` = 82; -- dranikhollowsb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5926; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5949; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5935; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 65; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5925; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 64; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5919; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5923; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5946; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5945; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5921; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5920; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 28; -- broodlands
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5937; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5938; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 395; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5939; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5940; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 17; -- barter
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5933; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5930; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5941; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5942; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5943; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5944; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5928; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 369; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5934; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 368; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5927; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5936; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5913; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5953; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5915; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5952; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5899; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5896; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5962; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5895; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5961; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5959; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5954; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5963; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5964; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5914; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5912; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5957; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5956; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5900; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5908; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5965; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5911; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5910; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5929; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5924; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5918; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5903; -- delveb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5909; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 145; -- guildhall
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5916; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5904; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5905; -- thenest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5906; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 146; -- guildlobby
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5917; -- stillmoona
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5907; -- stillmoonb
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5951; -- thundercrest
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5902; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5958; -- delvea
UPDATE `zone` SET `expansion` = 9 WHERE `id` = 5898; -- thundercrest
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6007; -- drachnidhive
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6004; -- drachnidhivea
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6001; -- illsalinb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6003; -- drachnidhivea
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6002; -- drachnidhiveb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5986; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6005; -- drachnidhivea
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6006; -- drachnidhive
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6000; -- illsalinb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5999; -- illsalinb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5998; -- illsalinb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5990; -- eastkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5989; -- shadowspine
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 432; -- westkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 433; -- westkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 434; -- westkorlachb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 435; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5988; -- drachnidhivec
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5987; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5985; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5984; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5983; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5991; -- eastkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5992; -- eastkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5994; -- corathusa
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5997; -- westkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5975; -- westkorlachb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5996; -- westkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5993; -- corathusa
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5976; -- westkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5977; -- westkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5995; -- westkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5978; -- corathusb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5979; -- corathusb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5980; -- dreadspire
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5981; -- illsalina
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 5982; -- westkorlachc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 247; -- nektulosa
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 335; -- shadowspine
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 101; -- eastkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 100; -- eastkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 96; -- dreadspire
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 72; -- drachnidhivea
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 71; -- drachnidhive
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 54; -- corathusb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 53; -- corathusa
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 52; -- corathus
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 74; -- drachnidhivec
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 73; -- drachnidhiveb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6008; -- drachnidhive
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 177; -- illsalin
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 178; -- illsalina
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 180; -- illsalinc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 179; -- illsalinb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6017; -- eastkorlach
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6016; -- illsalinc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6015; -- illsalinc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6014; -- illsalinc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6013; -- illsalinc
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6012; -- westkorlacha
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6011; -- corathusb
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6010; -- drachnidhive
UPDATE `zone` SET `expansion` = 10 WHERE `id` = 6009; -- drachnidhive
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 386; -- takishruinsa
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 130; -- freeportwest
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 67; -- devastation
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 310; -- ragea
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 309; -- rage
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 256; -- northro
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 105; -- elddar
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 106; -- elddara
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 129; -- freeporttheater
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 314; -- relic
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 128; -- freeporttemple
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 127; -- freeportsewers
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 126; -- freeportmilitia
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 124; -- freeporteast
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 123; -- freeportcityhall
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 122; -- freeportarena
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 121; -- freeportacademy
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 125; -- freeporthall
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 391; -- theater
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 392; -- theatera
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 346; -- skylance
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 385; -- takishruins
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 66; -- devastationa
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 8; -- arcstone
UPDATE `zone` SET `expansion` = 11 WHERE `id` = 360; -- southro
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 20; -- befallenb
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 183; -- innothuleb
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 411; -- toxxulia
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 425; -- vergalid
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 262; -- oceanoftears
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 175; -- icefall
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 371; -- stonehive
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 421; -- valdeholm
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 168; -- highpasskeep
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 373; -- sunderock
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 135; -- frostcrypt
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 167; -- highpasshold
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 50; -- commonlands
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 238; -- moors
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 55; -- crescent
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 318; -- roost
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 212; -- mesa
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 367; -- steppes
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 226; -- mistythicket
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 195; -- kithforest
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 68; -- direwind
UPDATE `zone` SET `expansion` = 12 WHERE `id` = 12; -- ashengate
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 209; -- maidensgrave
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 192; -- kattacastrum
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 24; -- blacksail
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 16; -- barren
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 237; -- monkeyrock
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 13; -- atiiki
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 185; -- jardelshook
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 343; -- silyssar
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 63; -- deadbone
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 340; -- shippvu
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 29; -- buriedsea
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 341; -- shipuvu
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 372; -- suncrest
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 390; -- thalassius
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 339; -- shipmvu
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 338; -- shipmvp
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 337; -- shipmvm
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 313; -- redfeather
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 438; -- zhisza
UPDATE `zone` SET `expansion` = 13 WHERE `id` = 358; -- solteris
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 59; -- crystallos
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 211; -- mechanotus
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 57; -- cryptofshade
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 342; -- shipworkshop
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 207; -- lopingplains
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 144; -- guardian
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 26; -- bloodmoon
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 158; -- gyrospireb
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 159; -- gyrospirez
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 169; -- hillsofshade
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 366; -- steamfontmts
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 210; -- mansion
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 364; -- steamfactory
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 76; -- dragonscaleb
UPDATE `zone` SET `expansion` = 14 WHERE `id` = 75; -- dragonscale
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 402; -- thevoidg
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 198; -- korascian
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 69; -- discord
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 70; -- discordtower
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 22; -- bertoxtemple
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 260; -- oceangreenhills
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 261; -- oceangreenvillage
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 399; -- thevoidd
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 398; -- thevoidc
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 272; -- oldkithicor
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 273; -- oldkurn
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 311; -- rathechamber
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 409; -- toskirakk
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 396; -- thevoida
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 298; -- precipiceofwar
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 397; -- thevoidb
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 400; -- thevoide
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 271; -- oldkaesorab
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 264; -- oldblackburrow
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 401; -- thevoidf
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 265; -- oldbloodfield
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 266; -- oldcommons
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 267; -- olddranik
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 268; -- oldfieldofbone
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 269; -- oldhighpass
UPDATE `zone` SET `expansion` = 15 WHERE `id` = 270; -- oldkaesoraa
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 446; -- brellsarena
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 448; -- convorteum
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 447; -- stonesnake
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 445; -- underquarry
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 444; -- foundation
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 443; -- arthicrex
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 442; -- pellucid
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 441; -- coolingchamber
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 440; -- brellsrest
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5878; -- weddingchapeldark
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5879; -- dragoncrypt
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5881; -- brellstemple
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5882; -- fungalforest
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5883; -- lichencreep
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5884; -- shiningcity
UPDATE `zone` SET `expansion` = 16 WHERE `id` = 5877; -- weddingchapel
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5563; -- somnium
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5565; -- thulehouse1
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5566; -- thulehouse2
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5567; -- well
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5568; -- neighborhood
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5557; -- morellcastle
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5562; -- miragulmare
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5561; -- housegarden
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5560; -- feerrott2
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5559; -- fallen
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5558; -- alkabormare
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5556; -- thulelibrary
UPDATE `zone` SET `expansion` = 17 WHERE `id` = 5564; -- thuledream
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5868; -- rubak
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5865; -- argath
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5875; -- eastsepulcher
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5874; -- sepulcher
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5873; -- cityofbronze
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5872; -- windsong
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5871; -- pillarsalra
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5870; -- resplendent
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5869; -- beastdomain
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5867; -- sarithcity
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5876; -- westsepulcher
UPDATE `zone` SET `expansion` = 18 WHERE `id` = 5866; -- arelis
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5894; -- xorbb
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5893; -- shardslanding
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5892; -- kaelshard
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5891; -- grelleth
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5890; -- eviltree
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5886; -- breedinggrounds
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5887; -- chapterhouse
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5888; -- crystalshard
UPDATE `zone` SET `expansion` = 19 WHERE `id` = 5889; -- eastwastesshard
