ALTER TABLE `raid_members` 
	ADD COLUMN `ismarker` TINYINT UNSIGNED DEFAULT(0) NOT NULL AFTER `islooter`,
	ADD COLUMN `isassister` TINYINT UNSIGNED DEFAULT(0) NOT NULL AFTER `ismarker`,
	ADD COLUMN `note` VARCHAR(64) DEFAULT("") NOT NULL AFTER `isassister`;

ALTER TABLE `raid_details` 
	ADD COLUMN `markedNPC1` SMALLINT UNSIGNED DEFAULT(0) NOT NULL AFTER `motd`,
	ADD COLUMN `markedNPC2` SMALLINT UNSIGNED DEFAULT(0) NOT NULL AFTER `markedNPC1`,
	ADD COLUMN `markedNPC3` SMALLINT UNSIGNED DEFAULT(0) NOT NULL AFTER `markedNPC2`;